"""Formal scaffolding paragraphs for the deterministic (non-LLM) draft path.

Why this module exists
----------------------
Two real drafts, generated by this app, side by side:

* An English **Mobile Theft Complaint** -- three pages, with a proper opening
  submission, a numbered statement of facts followed by a reading-instruction
  paragraph, a four-paragraph hedged Legal Position, a Consequences section,
  an enumerated Prayer with six procedural requests, and a Verification.
  It reads like something an advocate's office produced.

* A Hindi **धन वसूली नोटिस** (Recovery Notice) -- two pages, in which
  "कानूनी स्थिति" is a single sentence, "परिणाम" is one line, and the entire
  "प्रार्थना" section reads "उपलब्ध नहीं कराया गया।" It reads like a form
  someone half-filled.

Both came out of the same deterministic builder. The difference was one
condition in `LegalDraftEngine._deterministic_complaint_sections`::

    if template.category == "Complaint" and language in {"english", "hinglish"}:

The Hindi recovery notice failed *both* halves -- wrong category and wrong
language -- so it received none of the scaffolding, and every non-English user
and every non-Complaint document got a visibly second-class draft.

What this module changes, and what it deliberately does not
-----------------------------------------------------------
It supplies that scaffolding per **category** (a notice to a private party
must not talk about "the receiving authority", and a complaint must not
"reserve the right to initiate proceedings") and per **language**.

The original code's instinct was right and is kept: a Hindi document must
never be padded with English paragraphs. So scaffolding is applied only for
languages it has actually been authored in (`supports_scaffolding`), and any
other language keeps its concise localized fallback rather than a
mixed-language document. Adding a language here is purely additive.

Nothing here is generated, and nothing here asserts a fact. Every paragraph is
procedural or hedging -- it adds no event, person, date, amount, document,
loss or allegation. The user's own narrative remains the sole factual account
of the matter, exactly as before.

TRANSLATION PROVENANCE: the English text is carried over verbatim from the
paragraphs previously inlined in `engine.py`. The Hindi is authored here in
standard legal-drafting register. Like the rest of this codebase's
translations it has NOT been reviewed by a practising advocate, and should be
before this is relied on in production.
"""

from __future__ import annotations

# Languages with authored scaffolding. A language outside this set keeps the
# short localized fallback -- never a document with English paragraphs bolted
# onto Hindi/Tamil/Bengali prose. "hinglish" shares the English text by
# design: a Hinglish draft is written in Latin script with English legal
# terminology, so the English formal register is the correct one for it.
SCAFFOLDED_LANGUAGES = frozenset({"english", "hinglish", "hindi"})

# Categories that receive scaffolding. Affidavit and Contract are excluded on
# purpose: an affidavit's force comes from its sworn verification clause and a
# contract's from its operative terms, so neither is improved -- and both are
# arguably weakened -- by added procedural narration.
SCAFFOLDED_CATEGORIES = frozenset({"Complaint", "Notice", "Application"})


def supports_scaffolding(language: str, category: str) -> bool:
    return language in SCAFFOLDED_LANGUAGES and category in SCAFFOLDED_CATEGORIES


# Structure: category -> section heading -> language -> paragraph(s) appended
# to whatever the deterministic builder already produced for that section.
_SCAFFOLDING: dict[str, dict[str, dict[str, str]]] = {
    # ------------------------------------------------------------------
    # Complaint: addressed to a police station / commission / authority.
    # ------------------------------------------------------------------
    "Complaint": {
        "Introduction": {
            "english": (
                "This complaint is presented for being taken on the official record and considered by the "
                "competent authority in accordance with law. The description of the occurrence, the identity "
                "particulars and the relief requested below are confined to the information supplied by the "
                "applicant. Nothing in this draft is intended to enlarge that account, attribute a motive, or "
                "treat an allegation as an established finding."
            ),
            "hindi": (
                "यह शिकायत सक्षम प्राधिकारी के समक्ष विधि के अनुसार अभिलेख पर लिए जाने एवं विचारार्थ प्रस्तुत की जा "
                "रही है। नीचे वर्णित घटना का विवरण, पहचान संबंधी विवरण तथा वांछित अनुतोष पूर्णतः प्रार्थी द्वारा दी गई "
                "सूचना तक ही सीमित हैं। इस प्रारूप में उस कथन का विस्तार करने, किसी को आशय आरोपित करने, अथवा किसी "
                "अभिकथन को सिद्ध निष्कर्ष मानने का कोई अभिप्राय नहीं है।"
            ),
        },
        "Facts of the Case": {
            "english": (
                "The foregoing numbered statements constitute the applicant's account of the matter. They are "
                "requested to be read together with the case particulars stated above. The sequence is set out "
                "separately so that the date, place, persons or property identified by the applicant can be "
                "checked against the record during inquiry. No fact outside the applicant's supplied statement is "
                "asserted in this complaint."
                "\n\nThe applicant requests an opportunity to clarify any part of the statement that the receiving "
                "authority considers incomplete and, where required, to provide a supplementary statement. Any "
                "correction or additional factual detail should be recorded only after it is confirmed by the "
                "applicant."
            ),
            "hindi": (
                "उपरोक्त क्रमांकित कथन प्रार्थी का इस विषय संबंधी वृत्तांत हैं। इन्हें ऊपर वर्णित प्रकरण विवरण के साथ "
                "पढ़ा जाना अपेक्षित है। घटनाक्रम पृथक् रूप से इसलिए दिया गया है ताकि प्रार्थी द्वारा बताई गई तिथि, स्थान, "
                "व्यक्ति अथवा संपत्ति की जाँच के दौरान अभिलेख से पुष्टि की जा सके। इस शिकायत में प्रार्थी के दिए गए "
                "कथन से बाहर का कोई तथ्य अभिकथित नहीं है।"
                "\n\nप्रार्थी अनुरोध करता/करती है कि कथन के जिस अंश को प्राप्तकर्ता प्राधिकारी अपूर्ण समझे, उसे स्पष्ट "
                "करने तथा आवश्यकतानुसार पूरक कथन देने का अवसर प्रदान किया जाए। कोई भी संशोधन अथवा अतिरिक्त तथ्यात्मक "
                "विवरण प्रार्थी द्वारा पुष्टि किए जाने के उपरांत ही अभिलिखित किया जाए।"
            ),
        },
        "Legal Position": {
            # Trimmed (advocate-register redesign): this used to stack THREE
            # paragraphs re-hedging the same point the deterministic
            # builder's own `legal_position_hedged` phrase already makes
            # (engine.py's "prima facie appear to attract... no such
            # conclusion is asserted here") -- confirmed live, a real
            # complaint's Legal Position carried FOUR passages all saying
            # "mentioning the law doesn't prove anything" in slightly
            # different words. Kept the one paragraph doing genuinely NEW
            # procedural work (asking for accurate record-entry and evidence
            # preservation); cut the two that only restated the hedge.
            "english": (
                "For a fair consideration of the complaint, the applicant respectfully requests that the "
                "material particulars supplied above be entered accurately; that any jurisdictional or "
                "classification issue be assessed on the verified record; and that relevant material, if it exists "
                "and is lawfully available, be identified and preserved in accordance with the applicable "
                "procedure. This request is procedural in nature and does not assert that any particular item of "
                "evidence exists unless the applicant has expressly listed it."
            ),
            "hindi": (
                "शिकायत पर निष्पक्ष विचार हेतु प्रार्थी सादर अनुरोध करता/करती है कि ऊपर दिए गए सारभूत विवरण "
                "यथावत् अभिलिखित किए जाएँ; अधिकारिता अथवा वर्गीकरण संबंधी कोई प्रश्न सत्यापित अभिलेख के आधार पर "
                "निर्धारित किया जाए; तथा सुसंगत सामग्री, यदि विद्यमान एवं विधिपूर्वक उपलब्ध हो, तो लागू प्रक्रिया के "
                "अनुसार चिह्नित एवं संरक्षित की जाए। यह अनुरोध प्रक्रियात्मक प्रकृति का है और इससे यह अभिकथित नहीं "
                "होता कि कोई विशिष्ट साक्ष्य विद्यमान है, जब तक प्रार्थी ने उसे स्पष्टतः सूचीबद्ध न किया हो।"
            ),
        },
        "Consequences": {
            "english": (
                "Except for the effect expressly described in the applicant's own statement or quantified in the "
                "supplied fields, this complaint makes no additional claim of financial loss, injury, harassment "
                "or other damage. The request for intervention is based on the occurrence as narrated and the "
                "relief expressly sought by the applicant."
            ),
            "hindi": (
                "प्रार्थी के अपने कथन में स्पष्टतः वर्णित अथवा दिए गए विवरणों में परिमाणित प्रभाव के अतिरिक्त, यह "
                "शिकायत आर्थिक हानि, क्षति, उत्पीड़न अथवा अन्य नुकसान का कोई अतिरिक्त दावा नहीं करती। हस्तक्षेप का "
                "अनुरोध वर्णित घटना तथा प्रार्थी द्वारा स्पष्टतः वांछित अनुतोष पर ही आधारित है।"
            ),
        },
        "Prayer": {
            # Trimmed from 6 items to 3 (advocate-register redesign): items
            # 2 (dated acknowledgement) and 4 (permission to clarify/appear)
            # duplicated `_prayer_block`'s own `acknowledgement_request` and
            # `cooperation_undertaking` phrases word-for-word in substance;
            # item 3 (the authority will "examine" the complaint) added
            # nothing a reader doesn't already assume. Kept the three that
            # do genuinely distinct work: putting it on the official record,
            # preserving evidence, and being told the outcome. The trailing
            # disclaimer sentence is now one clause, not a fourth restatement
            # of "this isn't a new allegation" -- Legal Position and the
            # deterministic builder's own hedge already say that once each.
            "english": (
                "Without adding to or altering the relief stated above, the applicant further requests that the "
                "receiving authority:"
                "\n\n1. take this complaint and its stated particulars on the appropriate official record;"
                "\n\n2. preserve or obtain relevant records only to the extent permitted by law and considered "
                "necessary by the competent authority; and"
                "\n\n3. communicate the action taken or the appropriate procedural course to the applicant in "
                "accordance with law."
                "\n\nThese procedural requests are ancillary to the relief stated above."
            ),
            "hindi": (
                "ऊपर वर्णित अनुतोष में कोई वृद्धि अथवा परिवर्तन किए बिना, प्रार्थी यह भी अनुरोध करता/करती है कि "
                "प्राप्तकर्ता प्राधिकारी:"
                "\n\n1. इस शिकायत तथा इसमें वर्णित विवरणों को समुचित शासकीय अभिलेख पर लें;"
                "\n\n2. सुसंगत अभिलेखों को केवल उसी सीमा तक संरक्षित अथवा प्राप्त करें जितनी विधि द्वारा अनुज्ञेय हो "
                "तथा सक्षम प्राधिकारी द्वारा आवश्यक समझी जाए; तथा"
                "\n\n3. की गई कार्रवाई अथवा समुचित प्रक्रियात्मक मार्ग की सूचना प्रार्थी को विधि के अनुसार दें।"
                "\n\nये प्रक्रियात्मक अनुरोध ऊपर वर्णित अनुतोष के सहायक मात्र हैं।"
            ),
        },
    },
    # ------------------------------------------------------------------
    # Notice: addressed to a PRIVATE PARTY, not an authority. None of the
    # complaint wording above fits -- there is no "receiving authority", no
    # diary number, no inquiry. What a notice needs instead is a statement
    # of the sender's standing, an evidentiary basis, a hedged legal
    # foundation, and an express reservation of rights.
    # ------------------------------------------------------------------
    "Notice": {
        "Introduction": {
            "english": (
                "This notice is addressed to you formally and without prejudice to any right, remedy or contention "
                "available to the sender, all of which are expressly reserved. You are called upon to read the "
                "contents below carefully and to respond in writing to the demand set out in it."
            ),
            "hindi": (
                "यह सूचना आपको औपचारिक रूप से तथा प्रेषक को उपलब्ध किसी भी अधिकार, उपचार अथवा प्रतिवाद पर बिना "
                "किसी प्रतिकूल प्रभाव के दी जा रही है, जो सभी स्पष्टतः सुरक्षित रखे जाते हैं। आपसे अपेक्षा है कि नीचे "
                "वर्णित विषय-वस्तु को ध्यानपूर्वक पढ़ें तथा इसमें की गई माँग पर लिखित उत्तर दें।"
            ),
        },
        "Facts of the Case": {
            "english": (
                "The statements above are made on the basis of the sender's own record of the transaction and the "
                "correspondence exchanged between the parties. The sender is prepared to produce the supporting "
                "material before any competent forum should the matter proceed further."
                "\n\nIf you dispute any part of the account set out above, you are invited to state your "
                "position in writing, with particulars. No inference is drawn in this notice from a failure to "
                "reply, and nothing here treats silence as an admission of any fact stated above."
            ),
            "hindi": (
                "उपरोक्त कथन प्रेषक के अपने लेन-देन संबंधी अभिलेख तथा पक्षकारों के बीच हुए पत्राचार के आधार पर किए "
                "गए हैं। यदि विषय आगे बढ़ता है तो प्रेषक समर्थक सामग्री किसी भी सक्षम न्यायालय/मंच के समक्ष प्रस्तुत "
                "करने हेतु तत्पर है।"
                "\n\nयदि आप उपरोक्त वृत्तांत के किसी अंश को अस्वीकार करते हैं, तो आप अपना पक्ष विवरण सहित लिखित "
                "रूप में प्रस्तुत कर सकते हैं। उत्तर न देने से इस सूचना में कोई निष्कर्ष नहीं निकाला जा रहा है, और न ही "
                "मौन को उपरोक्त किसी तथ्य की स्वीकृति माना जा रहा है।"
            ),
        },
        "Legal Position": {
            "english": (
                "The statutory provisions referred to above are cited as the framework within which the sender's "
                "claim is asserted. Their mention does not by itself determine liability, which remains a matter "
                "for adjudication by a competent forum on the evidence placed before it."
                "\n\nThis notice is issued as a bona fide attempt to have the matter resolved directly between the "
                "parties, and should be treated as an opportunity to settle it without recourse to litigation. "
                "Nothing stated here is intended as a waiver of any right or remedy available to the sender."
            ),
            "hindi": (
                "ऊपर उल्लिखित सांविधिक प्रावधान उस विधिक ढाँचे के रूप में उद्धृत किए गए हैं जिसके अंतर्गत प्रेषक का "
                "दावा प्रस्तुत किया जा रहा है। इनका उल्लेख स्वतः दायित्व निर्धारित नहीं करता; दायित्व का निर्धारण "
                "सक्षम मंच द्वारा उसके समक्ष प्रस्तुत साक्ष्य के आधार पर ही किया जाएगा।"
                "\n\nयह सूचना विषय को पक्षकारों के बीच सीधे सुलझाने के सद्भावनापूर्ण प्रयास के रूप में जारी की जा रही "
                "है तथा इसे वाद-विवाद का सहारा लिए बिना मामला निपटाने के अवसर के रूप में लिया जाना चाहिए। यहाँ "
                "वर्णित किसी भी बात का आशय प्रेषक को उपलब्ध किसी अधिकार अथवा उपचार का परित्याग नहीं है।"
            ),
        },
        "Prayer": {
            "english": (
                "The sender reserves such rights and remedies as are available in law. Whether any particular "
                "proceeding lies, and what relief a forum may grant, is a matter for legal advice on the facts "
                "and for the forum to decide; no such proceeding, interest, cost or damages figure is asserted "
                "here. A copy of this notice is retained for record and for production before the appropriate "
                "forum if required."
            ),
            "hindi": (
                "प्रेषक विधि के अंतर्गत उपलब्ध अधिकार एवं उपचार सुरक्षित रखता/रखती है। कौन-सी कार्यवाही चलेगी तथा "
                "कोई मंच क्या अनुतोष देगा, यह तथ्यों पर विधिक परामर्श तथा संबंधित मंच के निर्णय का विषय है; इस "
                "सूचना में न कोई विशिष्ट कार्यवाही, न ब्याज, न व्यय और न ही क्षतिपूर्ति की कोई राशि अभिकथित की जा "
                "रही है। इस सूचना की एक प्रति अभिलेख हेतु तथा आवश्यकता पड़ने पर समुचित मंच के समक्ष प्रस्तुत करने "
                "हेतु सुरक्षित रखी गई है।"
            ),
        },
    },
    # ------------------------------------------------------------------
    # Application: addressed to an office/department for a sanction, record
    # or certificate. Neither adversarial nor investigative.
    # ------------------------------------------------------------------
    "Application": {
        "Introduction": {
            "english": (
                "This application is submitted for consideration and appropriate orders in accordance with the "
                "rules and procedure applicable to the subject matter. The particulars furnished below are true to "
                "the applicant's knowledge and are supplied solely to enable the request to be processed."
            ),
            "hindi": (
                "यह आवेदन विषय-वस्तु पर लागू नियमों एवं प्रक्रिया के अनुसार विचारार्थ तथा समुचित आदेश हेतु प्रस्तुत "
                "किया जा रहा है। नीचे दिए गए विवरण आवेदक की जानकारी के अनुसार सत्य हैं तथा केवल अनुरोध पर कार्रवाई "
                "किए जाने की सुविधा हेतु प्रस्तुत किए गए हैं।"
            ),
        },
        "Prayer": {
            "english": (
                "The applicant further requests that a dated acknowledgement of this application be issued, and "
                "that the applicant be informed of the decision or of any further document or clarification "
                "required, in accordance with the applicable procedure."
            ),
            "hindi": (
                "आवेदक यह भी अनुरोध करता/करती है कि इस आवेदन की दिनांकित पावती जारी की जाए, तथा लागू प्रक्रिया "
                "के अनुसार निर्णय अथवा अपेक्षित किसी अतिरिक्त दस्तावेज़ या स्पष्टीकरण की सूचना आवेदक को दी जाए।"
            ),
        },
    },
}


def apply_official_scaffolding(
    sections: dict[str, str], *, category: str, language: str
) -> dict[str, str]:
    """Append the formal paragraphs for `category` to `sections`, in place.

    A section that the deterministic builder did not produce at all is created
    only if the scaffolding for it is self-contained; sections whose
    scaffolding reads as a continuation ("The foregoing numbered statements
    ...") are skipped when there is nothing for them to continue, so a draft
    can never open a Facts section that has no facts in it.

    No-ops for any language/category outside `supports_scaffolding`, which is
    what keeps a Tamil or Bengali draft free of English paragraphs.
    """
    if not supports_scaffolding(language, category):
        return sections
    # "hinglish" is written in English legal register; share that text.
    text_language = "english" if language in ("english", "hinglish") else language
    # Sections whose scaffolding only makes sense appended to existing
    # content -- never used to create the section from nothing.
    continuation_only = {"Facts of the Case", "Consequences", "Legal Position"}
    for heading, translations in _SCAFFOLDING.get(category, {}).items():
        addition = translations.get(text_language)
        if not addition:
            continue
        existing = sections.get(heading, "").strip()
        if not existing and heading in continuation_only:
            continue
        sections[heading] = f"{existing}\n\n{addition}" if existing else addition
    return sections
