"""Part 58 "Answer Quality Audit" issues 16 & 23: making the strict-RAG
refusal actionable.

`NO_VERIFIED_CONTEXT_MESSAGES` is a hard guardrail -- when nothing in the
knowledge base clears the relevance gate, the system must not answer from
pre-trained knowledge. That part stays exactly as it is. What was wrong was
what the user was left with: someone typing "a man keeps phoning me,
harassing and threatening me -- how do I write a police complaint?" got a
bare "no verified document in the Knowledge Base" and nothing else. For an
urgent safety situation that is a failure of the product, not a display of
rigour.

This module supplies the missing half WITHOUT weakening the guardrail. It
adds no legal analysis, no statutory interpretation, and no claim about what
the law says -- only:

* Government of India emergency/reporting channels, which are published
  public-service numbers, cited by name so the user can verify them.
* Generic, jurisdiction-independent practical steps (preserve evidence,
  approach the police station, escalate to the Superintendent of Police,
  consult an advocate) that are true regardless of which provision applies.
* A pointer to a document this app can actually draft, when the question
  maps to one.

Everything here is a fixed, reviewed string. Nothing is generated by the LLM,
so nothing can be hallucinated into it.
"""

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class GuidanceCategory:
    key: str
    pattern: re.Pattern[str]
    # Draft template to offer, when this app has one for the situation.
    draft_id: str | None


# Ordered most-urgent-first: a message about being threatened AND defrauded
# should surface the personal-safety channel, not just the money one.
# Detection patterns (multilingual coverage pass, Sept 2026).
#
# The incident: a user asked, in Hindi, "मेरे बैंक खाते से बिना अनुमति
# ₹40,000 निकल गए हैं। मुझे तुरंत क्या करना चाहिए?" and got a bare "no
# verified document in the Knowledge Base" with no helplines, no steps, and
# no offer to draft anything. A Marathi user asking the same question got the
# same. The identical question in ENGLISH was matched and answered. The
# guardrail was working as designed; the guidance that is supposed to
# accompany it never fired, because these patterns covered English plus a few
# token Hindi phrases.
#
# Two concrete gaps, both fixed below:
#   * The Hindi cyber-fraud pattern required the literal "खाते से पैसे".
#     "खाते से बिना अनुमति ... निकल गए" -- the natural way to say it -- has
#     other words between "खाते से" and any money noun, so it never matched.
#   * Marathi, Gujarati, Tamil, Telugu, Kannada, Bengali, Punjabi, Malayalam,
#     Odia and Urdu had no cyber-fraud vocabulary at all.
#
# The verbs matter more than the nouns here: people describe this as money
# having "gone"/"been taken"/"been cut" far more often than they name a
# category like "fraud" or "cyber". Ordered most-urgent-first: a message about
# being threatened AND defrauded should surface the personal-safety channel,
# not just the money one.
_CATEGORIES: tuple[GuidanceCategory, ...] = (
    GuidanceCategory(
        "domestic_violence",
        re.compile(
            r"\b(domestic violence|husband beats?|in-?laws?|dowry|marital)\b"
            r"|घरेलू\s*हिंसा|दहेज|पति\s*(मारता|मारपीट)"
            r"|घरगुती\s*हिंसा|सासरच|हुंडा"
            r"|ઘરેલુ\s*હિંસા|દહેજ"
            r"|পারিবারিক\s*সহিংসতা|যৌতুক"
            r"|ਘਰੇਲੂ\s*ਹਿੰਸਾ|ਦਾਜ"
            r"|ଘରୋଇ\s*ହିଂସା|ଯୌତୁକ"
            r"|குடும்ப\s*வன்முறை|வரதட்சணை"
            r"|గృహ\s*హింస|కట్నం"
            r"|ಕೌಟುಂಬಿಕ\s*ದೌರ್ಜನ್ಯ|ವರದಕ್ಷಿಣೆ"
            r"|ഗാർഹിക\s*പീഡനം|സ്ത്രീധനം"
            r"|گھریلو\s*تشدد|جہیز",
            re.IGNORECASE,
        ),
        "domestic_violence_complaint",
    ),
    GuidanceCategory(
        "threat_harassment",
        re.compile(
            r"\b(threat(?:en(?:ing|ed)?|s)?|blackmail|extort|harass(?:ing|ment|ed)?|stalk(?:ing|er)?|abusive calls?)\b"
            r"|\b(dhamki|dhamka|pareshan|blackmail kar)\b"
            r"|धमकी|धमका|परेशान|पीछा\s*कर|ब्लैकमेल"
            r"|धमकाव|त्रास\s*देत|पाठलाग"
            r"|ધમકી|પરેશાન|બ્લેકમેલ"
            r"|হুমকি|উত্ত্যক্ত|ব্ল্যাকমেল"
            r"|ਧਮਕੀ|ਪਰੇਸ਼ਾਨ|ਬਲੈਕਮੇਲ"
            r"|ଧମକ|ହଇରାଣ"
            r"|மிரட்ட|தொல்லை|அச்சுறுத்த"
            r"|బెదిరింపు|వేధింపు"
            r"|ಬೆದರಿಕೆ|ಕಿರುಕುಳ"
            r"|ഭീഷണി|ഉപദ്രവ"
            r"|دھمکی|ہراسا|بلیک\s*میل",
            re.IGNORECASE,
        ),
        "threat_complaint",
    ),
    GuidanceCategory(
        "cyber_financial_fraud",
        re.compile(
            # English / romanised
            r"\b(cyber|fraud|fraudulent|defraud(?:ed)?|cheated|upi|otp|phishing|hacked|scam(?:med)?)\b"
            # Named payment rails people report by brand rather than by category.
            r"|\b(phonepe|paytm|gpay|google\s*pay|bhim|net\s*banking|netbanking|imps|neft|rtgs)\b"
            r"|\bunauthori[sz]ed\b|\bdebited\b|\bwithdrawn\b|\bdeducted\b"
            r"|\b(paisa kat|paise kat|paise nikal|account se paisa|account se paise|thagi|thaga)\b"
            # Hindi -- verb-led, so intervening words no longer break the match
            r"|साइबर|ऑनलाइन\s*(धोखा|ठगी|फ्रॉड)|ठगी|धोखाधड़ी"
            r"|खाते\s*से.{0,30}?(निकल|कट|काट|डेबिट|ट्रांसफर)"
            r"|(निकल\s*गए|कट\s*गए|डेबिट\s*हो).{0,30}?(खाते|अकाउंट|बैंक)"
            r"|बिना\s*(अनुमति|इजाज़त|इजाजत|मंजूरी)"
            r"|अनधिकृत\s*(लेनदेन|निकासी|भुगतान)"
            # Marathi
            r"|सायबर|खात्यातून.{0,30}?(काढ|कट|वजा|डेबिट)|परवानगीशिवाय|फसवणूक"
            # Gujarati
            r"|સાયબર|સાયબર\s*છેતરપિંડી|છેતરપિંડી|ખાતામાંથી.{0,30}?(ઉપડ|કપા|ડેબિટ)|પરવાનગી\s*વગર"
            # Bengali
            r"|সাইবার|প্রতারণা|জালিয়াতি|অ্যাকাউন্ট\s*থেকে.{0,30}?(কেটে|তোলা|ডেবিট)|অনুমতি\s*ছাড়া"
            # Punjabi
            r"|ਸਾਈਬਰ|ਧੋਖਾਧੜੀ|ਠੱਗੀ|ਖਾਤੇ\s*ਵਿੱਚੋਂ.{0,30}?(ਨਿਕਲ|ਕੱਟ|ਡੈਬਿਟ)|ਬਿਨਾਂ\s*ਇਜਾਜ਼ਤ"
            # Odia
            r"|ସାଇବର|ପ୍ରତାରଣା|ଠକେଇ|ଖାତାରୁ.{0,30}?(କଟି|ଉଠି|ଡେବିଟ)|ଅନୁମତି\s*ବିନା"
            # Tamil
            r"|இணையவழி\s*மோசடி|சைபர்|மோசடி|கணக்கிலிருந்து.{0,30}?(எடுக்க|கழிக்க|பறி)|அனுமதி\s*இன்றி"
            # Telugu
            r"|సైబర్|మోసం|ఖాతా\s*నుండి.{0,30}?(తీసి|కట్|డెబిట)|అనుమతి\s*లేకుండా"
            # Kannada
            r"|ಸೈಬರ್|ವಂಚನೆ|ಖಾತೆಯಿಂದ.{0,30}?(ಹಣ|ಕಡಿತ|ಡೆಬಿಟ)|ಅನುಮತಿ\s*ಇಲ್ಲದೆ"
            # Malayalam
            r"|സൈബർ|തട്ടിപ്പ്|അക്കൗണ്ടിൽ\s*നിന്ന്.{0,30}?(പിൻവലി|കുറ|ഡെബിറ്റ)|അനുമതി\s*ഇല്ലാതെ"
            # Urdu
            r"|سائبر|دھوکہ\s*دہی|فراڈ|اکاؤنٹ\s*سے.{0,30}?(نکل|کٹ|ڈیبٹ)|بغیر\s*اجازت",
            re.IGNORECASE,
        ),
        "cyber_crime_complaint",
    ),
)

# Government of India public-service channels, named so the user can verify
# each one independently. Deliberately not translated as numbers/URLs.
_CHANNELS: dict[str, tuple[str, ...]] = {
    "domestic_violence": (
        "112 (national emergency)",
        "181 (Women Helpline)",
        "1091 (Women's Police Helpline)",
    ),
    "threat_harassment": (
        "112 (national emergency)",
        "1930 / cybercrime.gov.in (National Cyber Crime Reporting Portal, if the threats arrive by phone or online)",
    ),
    "cyber_financial_fraud": (
        "1930 (Cyber Crime Financial Fraud Helpline)",
        "cybercrime.gov.in (National Cyber Crime Reporting Portal)",
        "112 (national emergency)",
    ),
}

_STEPS: dict[str, dict[str, tuple[str, ...]]] = {
    "english": {
        "domestic_violence": (
            "If you are in immediate danger, call the emergency numbers above first — reporting can follow.",
            "Preserve anything that records what happened: medical records, photographs, messages, and the names of anyone who witnessed it.",
            "A written complaint can be given at the nearest police station, and a Protection Officer/service provider in your district can also receive it.",
            "Speak to a qualified advocate about the specific reliefs available in your situation.",
        ),
        "threat_harassment": (
            "If you feel unsafe right now, call the emergency numbers above before anything else.",
            "Preserve the evidence exactly as received — do not delete anything. Keep call logs, screenshots of messages, recordings, dates, times, and the number the calls come from.",
            "Give a written complaint at the police station with jurisdiction, and keep a stamped/acknowledged copy with its receipt number.",
            "If the police station does not register your complaint, the same complaint can be sent in writing to the Superintendent of Police.",
            "Speak to a qualified advocate about which provisions apply to your specific facts.",
        ),
        "cyber_financial_fraud": (
            "Report the transaction to your bank immediately and ask, in writing, for the account/card to be blocked — the earlier a fraudulent transfer is reported, the more likely it can be stopped.",
            "Preserve the evidence: transaction IDs/UTR numbers, bank SMS alerts, statements, screenshots, and any chat or call records with the person involved.",
            "File on the National Cyber Crime Reporting Portal and at the nearest cyber crime cell/police station, and keep the acknowledgement number.",
            "Speak to a qualified advocate about recovery and the provisions that apply to your specific facts.",
        ),
    },
    "hindi": {
        "domestic_violence": (
            "यदि आप तत्काल खतरे में हैं, तो पहले ऊपर दिए गए आपातकालीन नंबरों पर कॉल करें — शिकायत बाद में दर्ज की जा सकती है।",
            "जो कुछ हुआ उसका रिकॉर्ड सुरक्षित रखें: मेडिकल रिपोर्ट, तस्वीरें, संदेश, और गवाहों के नाम।",
            "लिखित शिकायत निकटतम पुलिस थाने में दी जा सकती है; आपके जिले का संरक्षण अधिकारी/सेवा प्रदाता भी इसे ले सकता है।",
            "आपकी स्थिति में उपलब्ध राहतों के बारे में किसी योग्य अधिवक्ता से बात करें।",
        ),
        "threat_harassment": (
            "अगर आप अभी असुरक्षित महसूस कर रहे हैं, तो सबसे पहले ऊपर दिए गए आपातकालीन नंबरों पर कॉल करें।",
            "सबूत जैसे मिले वैसे ही सुरक्षित रखें — कुछ भी न मिटाएँ। कॉल लॉग, संदेशों के स्क्रीनशॉट, रिकॉर्डिंग, तारीख-समय और वह नंबर संभालकर रखें जिससे कॉल आ रहे हैं।",
            "संबंधित क्षेत्राधिकार वाले पुलिस थाने में लिखित शिकायत दें और रसीद संख्या सहित उसकी प्राप्ति-प्रति अपने पास रखें।",
            "यदि थाना शिकायत दर्ज न करे, तो वही शिकायत लिखित रूप में पुलिस अधीक्षक को भेजी जा सकती है।",
            "आपके विशिष्ट तथ्यों पर कौन-से प्रावधान लागू होते हैं, इस बारे में किसी योग्य अधिवक्ता से बात करें।",
        ),
        "cyber_financial_fraud": (
            "लेनदेन की सूचना तुरंत अपने बैंक को दें और लिखित में खाता/कार्ड ब्लॉक करने का अनुरोध करें — धोखाधड़ी जितनी जल्दी रिपोर्ट होगी, रकम रुकने की संभावना उतनी अधिक होगी।",
            "सबूत सुरक्षित रखें: ट्रांजैक्शन आईडी/UTR नंबर, बैंक के SMS अलर्ट, स्टेटमेंट, स्क्रीनशॉट, और संबंधित व्यक्ति से हुई चैट या कॉल का रिकॉर्ड।",
            "राष्ट्रीय साइबर क्राइम रिपोर्टिंग पोर्टल पर और निकटतम साइबर सेल/पुलिस थाने में शिकायत दर्ज करें, और पावती संख्या संभालकर रखें।",
            "वसूली और आपके तथ्यों पर लागू प्रावधानों के बारे में किसी योग्य अधिवक्ता से बात करें।",
        ),
    },
    "hinglish": {
        "domestic_violence": (
            "Agar aap turant khatre mein hain, to pehle upar diye gaye emergency numbers par call karein — complaint baad mein bhi ho sakti hai.",
            "Jo hua uska record safe rakhein: medical reports, photos, messages, aur gawahon ke naam.",
            "Likhit complaint nazdeeki police station mein di ja sakti hai; aapke district ka Protection Officer/service provider bhi le sakta hai.",
            "Aapki situation mein available reliefs ke baare mein kisi qualified advocate se baat karein.",
        ),
        "threat_harassment": (
            "Agar aap abhi unsafe feel kar rahe hain, to sabse pehle upar diye gaye emergency numbers par call karein.",
            "Evidence jaise mila waise hi safe rakhein — kuch delete na karein. Call logs, messages ke screenshots, recordings, date-time, aur wo number sambhal kar rakhein jisse calls aa rahe hain.",
            "Jurisdiction wale police station mein likhit complaint dein aur receipt number ke saath acknowledged copy apne paas rakhein.",
            "Agar police station complaint register na kare, to wahi complaint likhit roop mein Superintendent of Police ko bheji ja sakti hai.",
            "Aapke specific facts par kaun se provisions lagte hain, iske liye kisi qualified advocate se baat karein.",
        ),
        "cyber_financial_fraud": (
            "Transaction ki jaankari turant apne bank ko dein aur likhit mein account/card block karne ko kahein — fraud jitni jaldi report hoga, paisa rukne ke chances utne zyada hain.",
            "Evidence safe rakhein: transaction ID/UTR number, bank SMS alerts, statements, screenshots, aur us vyakti se hui chat ya call ka record.",
            "National Cyber Crime Reporting Portal par aur nazdeeki cyber cell/police station mein complaint file karein, aur acknowledgement number sambhal kar rakhein.",
            "Recovery aur aapke facts par lagne wale provisions ke baare mein kisi qualified advocate se baat karein.",
        ),
    },
    "marathi": {
        "domestic_violence": (
            "तुम्ही तात्काळ धोक्यात असाल तर आधी वरील आपत्कालीन क्रमांकांवर संपर्क साधा — तक्रार नंतरही करता येते.",
            "जे घडले त्याचा पुरावा जपून ठेवा: वैद्यकीय कागदपत्रे, छायाचित्रे, संदेश आणि साक्षीदारांची नावे.",
            "लेखी तक्रार जवळच्या पोलीस ठाण्यात देता येते; तुमच्या जिल्ह्यातील संरक्षण अधिकारी/सेवा पुरवठादारही ती स्वीकारू शकतात.",
            "तुमच्या परिस्थितीत उपलब्ध दिलाशांबाबत पात्र वकिलाशी बोला.",
        ),
        "threat_harassment": (
            "तुम्हाला आत्ता असुरक्षित वाटत असेल, तर सर्वप्रथम वरील आपत्कालीन क्रमांकांवर संपर्क साधा.",
            "पुरावा जसाच्या तसा जपून ठेवा — काहीही हटवू नका. कॉल लॉग, संदेशांचे स्क्रीनशॉट, रेकॉर्डिंग, तारीख-वेळ आणि ज्या क्रमांकावरून कॉल येतात तो क्रमांक जपा.",
            "संबंधित हद्दीच्या पोलीस ठाण्यात लेखी तक्रार द्या आणि पावती क्रमांकासह स्वीकृत प्रत स्वतःजवळ ठेवा.",
            "पोलीस ठाण्याने तक्रार नोंदवली नाही, तर तीच तक्रार लेखी स्वरूपात पोलीस अधीक्षकांकडे पाठवता येते.",
        ),
        "cyber_financial_fraud": (
            "व्यवहाराची माहिती तात्काळ तुमच्या बँकेला द्या आणि खाते/कार्ड ब्लॉक करण्याची विनंती लेखी स्वरूपात करा — फसवणूक जितक्या लवकर कळवाल तितकी रक्कम थांबण्याची शक्यता जास्त.",
            "पुरावा जपून ठेवा: व्यवहार क्रमांक/UTR क्रमांक, बँकेचे SMS अलर्ट, स्टेटमेंट, स्क्रीनशॉट आणि संबंधित व्यक्तीशी झालेल्या चॅट किंवा कॉलचा तपशील.",
            "राष्ट्रीय सायबर क्राईम रिपोर्टिंग पोर्टलवर आणि जवळच्या सायबर सेल/पोलीस ठाण्यात तक्रार नोंदवा, आणि पोचपावती क्रमांक जपून ठेवा.",
            "रक्कम परत मिळवण्याबाबत आणि तुमच्या तथ्यांना लागू होणाऱ्या तरतुदींबाबत पात्र वकिलाशी बोला.",
        ),
    },
    "gujarati": {
        "domestic_violence": (
            "જો તમે તાત્કાલિક જોખમમાં હો, તો પહેલાં ઉપર આપેલા કટોકટી નંબરો પર કૉલ કરો — ફરિયાદ પછી પણ થઈ શકે છે.",
            "જે બન્યું તેનો પુરાવો સાચવો: તબીબી અહેવાલો, ફોટા, સંદેશા અને સાક્ષીઓનાં નામ.",
            "લેખિત ફરિયાદ નજીકના પોલીસ સ્ટેશનમાં આપી શકાય છે; તમારા જિલ્લાના પ્રોટેક્શન ઓફિસર/સેવા પ્રદાતા પણ તે સ્વીકારી શકે છે.",
            "તમારી પરિસ્થિતિમાં ઉપલબ્ધ રાહતો વિશે લાયક વકીલ સાથે વાત કરો.",
        ),
        "threat_harassment": (
            "જો તમે અત્યારે અસુરક્ષિત અનુભવતા હો, તો સૌથી પહેલાં ઉપર આપેલા કટોકટી નંબરો પર કૉલ કરો.",
            "પુરાવો જેમ મળ્યો તેમ સાચવો — કંઈ પણ કાઢી ન નાખો. કૉલ લોગ, સંદેશાના સ્ક્રીનશોટ, રેકોર્ડિંગ, તારીખ-સમય અને જે નંબર પરથી કૉલ આવે છે તે સાચવો.",
            "સંબંધિત હદના પોલીસ સ્ટેશનમાં લેખિત ફરિયાદ આપો અને રસીદ નંબર સાથે સ્વીકૃત નકલ તમારી પાસે રાખો.",
            "જો પોલીસ સ્ટેશન ફરિયાદ નોંધે નહીં, તો એ જ ફરિયાદ લેખિતમાં પોલીસ અધિક્ષકને મોકલી શકાય છે.",
        ),
        "cyber_financial_fraud": (
            "વ્યવહારની જાણ તરત તમારી બેંકને કરો અને ખાતું/કાર્ડ બ્લોક કરવા લેખિતમાં જણાવો — છેતરપિંડી જેટલી વહેલી જણાવશો તેટલી રકમ અટકવાની શક્યતા વધુ.",
            "પુરાવો સાચવો: ટ્રાન્ઝેક્શન આઈડી/UTR નંબર, બેંકના SMS એલર્ટ, સ્ટેટમેન્ટ, સ્ક્રીનશોટ અને સંબંધિત વ્યક્તિ સાથેની ચેટ કે કૉલનો રેકોર્ડ.",
            "નેશનલ સાયબર ક્રાઈમ રિપોર્ટિંગ પોર્ટલ પર અને નજીકના સાયબર સેલ/પોલીસ સ્ટેશનમાં ફરિયાદ નોંધાવો, અને સ્વીકૃતિ નંબર સાચવો.",
            "રકમ પરત મેળવવા અંગે અને તમારી હકીકતોને લાગુ પડતી જોગવાઈઓ અંગે લાયક વકીલ સાથે વાત કરો.",
        ),
    },
    "bengali": {
        "domestic_violence": (
            "আপনি যদি তাৎক্ষণিক বিপদে থাকেন, তবে আগে উপরের জরুরি নম্বরে ফোন করুন — অভিযোগ পরেও করা যাবে।",
            "যা ঘটেছে তার প্রমাণ সংরক্ষণ করুন: চিকিৎসা নথি, ছবি, বার্তা এবং সাক্ষীদের নাম।",
            "লিখিত অভিযোগ নিকটবর্তী থানায় দেওয়া যায়; আপনার জেলার প্রোটেকশন অফিসার/সেবা প্রদানকারীও তা গ্রহণ করতে পারেন।",
            "আপনার পরিস্থিতিতে প্রাপ্য প্রতিকার সম্পর্কে যোগ্য আইনজীবীর সঙ্গে কথা বলুন।",
        ),
        "threat_harassment": (
            "এখনই অনিরাপদ বোধ করলে সবার আগে উপরের জরুরি নম্বরে ফোন করুন।",
            "প্রমাণ যেমন আছে তেমনই রাখুন — কিছু মুছবেন না। কল লগ, বার্তার স্ক্রিনশট, রেকর্ডিং, তারিখ-সময় এবং যে নম্বর থেকে ফোন আসছে তা সংরক্ষণ করুন।",
            "এখতিয়ারভুক্ত থানায় লিখিত অভিযোগ দিন এবং রসিদ নম্বরসহ স্বীকৃত কপি নিজের কাছে রাখুন।",
            "থানা অভিযোগ নথিভুক্ত না করলে, একই অভিযোগ লিখিতভাবে পুলিশ সুপারের কাছে পাঠানো যায়।",
        ),
        "cyber_financial_fraud": (
            "লেনদেনের কথা অবিলম্বে আপনার ব্যাঙ্ককে জানান এবং লিখিতভাবে অ্যাকাউন্ট/কার্ড ব্লক করতে বলুন — প্রতারণা যত দ্রুত জানানো হবে, টাকা আটকানোর সম্ভাবনা তত বেশি।",
            "প্রমাণ সংরক্ষণ করুন: ট্রানজ্যাকশন আইডি/UTR নম্বর, ব্যাঙ্কের SMS অ্যালার্ট, স্টেটমেন্ট, স্ক্রিনশট এবং সংশ্লিষ্ট ব্যক্তির সঙ্গে চ্যাট বা কলের রেকর্ড।",
            "জাতীয় সাইবার ক্রাইম রিপোর্টিং পোর্টালে এবং নিকটবর্তী সাইবার সেল/থানায় অভিযোগ দায়ের করুন, এবং স্বীকৃতি নম্বর সংরক্ষণ করুন।",
            "টাকা উদ্ধার এবং আপনার ঘটনার ক্ষেত্রে প্রযোজ্য বিধান সম্পর্কে যোগ্য আইনজীবীর সঙ্গে কথা বলুন।",
        ),
    },
    "tamil": {
        "domestic_violence": (
            "நீங்கள் உடனடி ஆபத்தில் இருந்தால், முதலில் மேலே உள்ள அவசர எண்களை அழைக்கவும் — புகார் பின்னரும் அளிக்கலாம்.",
            "நடந்ததற்கான ஆதாரங்களைப் பாதுகாக்கவும்: மருத்துவப் பதிவுகள், புகைப்படங்கள், செய்திகள் மற்றும் சாட்சிகளின் பெயர்கள்.",
            "அருகிலுள்ள காவல் நிலையத்தில் எழுத்துப்பூர்வ புகார் அளிக்கலாம்; உங்கள் மாவட்டப் பாதுகாப்பு அலுவலர்/சேவை வழங்குநரும் அதைப் பெறலாம்.",
            "உங்கள் நிலையில் கிடைக்கக்கூடிய நிவாரணங்கள் குறித்து தகுதியான வழக்கறிஞரிடம் பேசவும்.",
        ),
        "threat_harassment": (
            "இப்போது பாதுகாப்பற்றதாக உணர்ந்தால், முதலில் மேலே உள்ள அவசர எண்களை அழைக்கவும்.",
            "ஆதாரங்களைக் கிடைத்தபடியே பாதுகாக்கவும் — எதையும் அழிக்க வேண்டாம். அழைப்புப் பதிவுகள், செய்திகளின் திரைப்பிடிப்புகள், பதிவுகள், தேதி-நேரம் மற்றும் அழைப்பு வரும் எண்ணைப் பாதுகாக்கவும்.",
            "அதிகார எல்லைக்குட்பட்ட காவல் நிலையத்தில் எழுத்துப்பூர்வ புகார் அளித்து, ரசீது எண்ணுடன் ஒப்புகைப் பிரதியை வைத்திருக்கவும்.",
            "காவல் நிலையம் புகாரைப் பதிவு செய்யவில்லை எனில், அதே புகாரை எழுத்து வடிவில் காவல் கண்காணிப்பாளருக்கு அனுப்பலாம்.",
        ),
        "cyber_financial_fraud": (
            "பரிவர்த்தனை குறித்து உடனடியாக உங்கள் வங்கிக்குத் தெரிவித்து, கணக்கு/அட்டையை முடக்கக் கோரி எழுத்துப்பூர்வமாகக் கேட்கவும் — மோசடி எவ்வளவு விரைவில் தெரிவிக்கப்படுகிறதோ, பணத்தை நிறுத்தும் வாய்ப்பு அவ்வளவு அதிகம்.",
            "ஆதாரங்களைப் பாதுகாக்கவும்: பரிவர்த்தனை ஐடி/UTR எண், வங்கியின் SMS அறிவிப்புகள், அறிக்கைகள், திரைப்பிடிப்புகள் மற்றும் தொடர்புடையவருடனான அரட்டை அல்லது அழைப்புப் பதிவுகள்.",
            "தேசிய சைபர் கிரைம் ரிப்போர்ட்டிங் போர்ட்டலிலும் அருகிலுள்ள சைபர் பிரிவு/காவல் நிலையத்திலும் புகார் அளித்து, ஒப்புகை எண்ணைப் பாதுகாக்கவும்.",
            "பணத்தை மீட்பது குறித்தும், உங்கள் நிகழ்வுக்குப் பொருந்தும் சட்டப் பிரிவுகள் குறித்தும் தகுதியான வழக்கறிஞரிடம் பேசவும்.",
        ),
    },
    "telugu": {
        "domestic_violence": (
            "మీరు తక్షణ ప్రమాదంలో ఉంటే, ముందుగా పైన ఇచ్చిన అత్యవసర నంబర్లకు కాల్ చేయండి — ఫిర్యాదు తర్వాత కూడా చేయవచ్చు.",
            "జరిగినదానికి సంబంధించిన ఆధారాలను భద్రపరచండి: వైద్య రికార్డులు, ఫోటోలు, సందేశాలు మరియు సాక్షుల పేర్లు.",
            "సమీప పోలీస్ స్టేషన్‌లో లిఖితపూర్వక ఫిర్యాదు ఇవ్వవచ్చు; మీ జిల్లా రక్షణ అధికారి/సేవా ప్రదాత కూడా దానిని స్వీకరించవచ్చు.",
            "మీ పరిస్థితిలో అందుబాటులో ఉన్న ఉపశమనాల గురించి అర్హతగల న్యాయవాదితో మాట్లాడండి.",
        ),
        "threat_harassment": (
            "మీరు ఇప్పుడు అసురక్షితంగా భావిస్తే, ముందుగా పైన ఇచ్చిన అత్యవసర నంబర్లకు కాల్ చేయండి.",
            "ఆధారాలను ఉన్నది ఉన్నట్లుగా భద్రపరచండి — దేనినీ తొలగించవద్దు. కాల్ లాగ్‌లు, సందేశాల స్క్రీన్‌షాట్‌లు, రికార్డింగ్‌లు, తేదీ-సమయం మరియు కాల్ వస్తున్న నంబర్‌ను భద్రపరచండి.",
            "పరిధిలోని పోలీస్ స్టేషన్‌లో లిఖితపూర్వక ఫిర్యాదు ఇచ్చి, రసీదు నంబర్‌తో సహా అంగీకరించిన కాపీని మీ వద్ద ఉంచుకోండి.",
            "పోలీస్ స్టేషన్ ఫిర్యాదును నమోదు చేయకపోతే, అదే ఫిర్యాదును లిఖితపూర్వకంగా పోలీస్ సూపరింటెండెంట్‌కు పంపవచ్చు.",
        ),
        "cyber_financial_fraud": (
            "లావాదేవీ గురించి వెంటనే మీ బ్యాంకుకు తెలియజేసి, ఖాతా/కార్డును బ్లాక్ చేయమని లిఖితపూర్వకంగా కోరండి — మోసాన్ని ఎంత త్వరగా తెలియజేస్తే, డబ్బు ఆగే అవకాశం అంత ఎక్కువ.",
            "ఆధారాలను భద్రపరచండి: లావాదేవీ ఐడీ/UTR నంబర్, బ్యాంకు SMS హెచ్చరికలు, స్టేట్‌మెంట్లు, స్క్రీన్‌షాట్‌లు మరియు సంబంధిత వ్యక్తితో జరిగిన చాట్ లేదా కాల్ రికార్డు.",
            "జాతీయ సైబర్ క్రైమ్ రిపోర్టింగ్ పోర్టల్‌లో మరియు సమీప సైబర్ సెల్/పోలీస్ స్టేషన్‌లో ఫిర్యాదు చేసి, రసీదు నంబర్‌ను భద్రపరచండి.",
            "డబ్బు రికవరీ గురించి మరియు మీ వాస్తవాలకు వర్తించే నిబంధనల గురించి అర్హతగల న్యాయవాదితో మాట్లాడండి.",
        ),
    },
    "kannada": {
        "domestic_violence": (
            "ನೀವು ತಕ್ಷಣದ ಅಪಾಯದಲ್ಲಿದ್ದರೆ, ಮೊದಲು ಮೇಲಿನ ತುರ್ತು ಸಂಖ್ಯೆಗಳಿಗೆ ಕರೆ ಮಾಡಿ — ದೂರನ್ನು ನಂತರವೂ ನೀಡಬಹುದು.",
            "ನಡೆದದ್ದರ ಪುರಾವೆಗಳನ್ನು ಸಂರಕ್ಷಿಸಿ: ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು, ಛಾಯಾಚಿತ್ರಗಳು, ಸಂದೇಶಗಳು ಮತ್ತು ಸಾಕ್ಷಿಗಳ ಹೆಸರುಗಳು.",
            "ಹತ್ತಿರದ ಪೊಲೀಸ್ ಠಾಣೆಯಲ್ಲಿ ಲಿಖಿತ ದೂರು ನೀಡಬಹುದು; ನಿಮ್ಮ ಜಿಲ್ಲೆಯ ಸಂರಕ್ಷಣಾ ಅಧಿಕಾರಿ/ಸೇವಾ ಪೂರೈಕೆದಾರರೂ ಅದನ್ನು ಸ್ವೀಕರಿಸಬಹುದು.",
            "ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ ಲಭ್ಯವಿರುವ ಪರಿಹಾರಗಳ ಬಗ್ಗೆ ಅರ್ಹ ವಕೀಲರೊಂದಿಗೆ ಮಾತನಾಡಿ.",
        ),
        "threat_harassment": (
            "ನೀವು ಈಗ ಅಸುರಕ್ಷಿತ ಎನಿಸಿದರೆ, ಮೊದಲು ಮೇಲಿನ ತುರ್ತು ಸಂಖ್ಯೆಗಳಿಗೆ ಕರೆ ಮಾಡಿ.",
            "ಪುರಾವೆಗಳನ್ನು ಸಿಕ್ಕಂತೆಯೇ ಇರಿಸಿ — ಏನನ್ನೂ ಅಳಿಸಬೇಡಿ. ಕರೆ ದಾಖಲೆಗಳು, ಸಂದೇಶಗಳ ಸ್ಕ್ರೀನ್‌ಶಾಟ್‌ಗಳು, ಧ್ವನಿಮುದ್ರಣಗಳು, ದಿನಾಂಕ-ಸಮಯ ಮತ್ತು ಕರೆ ಬರುತ್ತಿರುವ ಸಂಖ್ಯೆಯನ್ನು ಇರಿಸಿಕೊಳ್ಳಿ.",
            "ವ್ಯಾಪ್ತಿಯ ಪೊಲೀಸ್ ಠಾಣೆಯಲ್ಲಿ ಲಿಖಿತ ದೂರು ನೀಡಿ, ರಸೀದಿ ಸಂಖ್ಯೆ ಸಹಿತ ಸ್ವೀಕೃತ ಪ್ರತಿಯನ್ನು ನಿಮ್ಮ ಬಳಿ ಇರಿಸಿಕೊಳ್ಳಿ.",
            "ಪೊಲೀಸ್ ಠಾಣೆ ದೂರನ್ನು ದಾಖಲಿಸದಿದ್ದರೆ, ಅದೇ ದೂರನ್ನು ಲಿಖಿತವಾಗಿ ಪೊಲೀಸ್ ವರಿಷ್ಠಾಧಿಕಾರಿಗೆ ಕಳುಹಿಸಬಹುದು.",
        ),
        "cyber_financial_fraud": (
            "ವಹಿವಾಟಿನ ಬಗ್ಗೆ ತಕ್ಷಣ ನಿಮ್ಮ ಬ್ಯಾಂಕಿಗೆ ತಿಳಿಸಿ ಮತ್ತು ಖಾತೆ/ಕಾರ್ಡ್ ಬ್ಲಾಕ್ ಮಾಡಲು ಲಿಖಿತವಾಗಿ ಕೋರಿ — ವಂಚನೆಯನ್ನು ಎಷ್ಟು ಬೇಗ ವರದಿ ಮಾಡಿದರೆ ಹಣ ನಿಲ್ಲುವ ಸಾಧ್ಯತೆ ಅಷ್ಟು ಹೆಚ್ಚು.",
            "ಪುರಾವೆಗಳನ್ನು ಸಂರಕ್ಷಿಸಿ: ವಹಿವಾಟು ಐಡಿ/UTR ಸಂಖ್ಯೆ, ಬ್ಯಾಂಕ್ SMS ಎಚ್ಚರಿಕೆಗಳು, ಸ್ಟೇಟ್‌ಮೆಂಟ್‌ಗಳು, ಸ್ಕ್ರೀನ್‌ಶಾಟ್‌ಗಳು ಮತ್ತು ಸಂಬಂಧಪಟ್ಟ ವ್ಯಕ್ತಿಯೊಂದಿಗಿನ ಚಾಟ್ ಅಥವಾ ಕರೆ ದಾಖಲೆ.",
            "ರಾಷ್ಟ್ರೀಯ ಸೈಬರ್ ಕ್ರೈಂ ರಿಪೋರ್ಟಿಂಗ್ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಮತ್ತು ಹತ್ತಿರದ ಸೈಬರ್ ಸೆಲ್/ಪೊಲೀಸ್ ಠಾಣೆಯಲ್ಲಿ ದೂರು ದಾಖಲಿಸಿ, ಸ್ವೀಕೃತಿ ಸಂಖ್ಯೆಯನ್ನು ಇರಿಸಿಕೊಳ್ಳಿ.",
            "ಹಣ ವಸೂಲಾತಿ ಮತ್ತು ನಿಮ್ಮ ಪ್ರಕರಣಕ್ಕೆ ಅನ್ವಯಿಸುವ ಉಪಬಂಧಗಳ ಬಗ್ಗೆ ಅರ್ಹ ವಕೀಲರೊಂದಿಗೆ ಮಾತನಾಡಿ.",
        ),
    },
    "malayalam": {
        "domestic_violence": (
            "നിങ്ങൾ ഉടനടി അപകടത്തിലാണെങ്കിൽ, ആദ്യം മുകളിലുള്ള അടിയന്തര നമ്പറുകളിൽ വിളിക്കുക — പരാതി പിന്നീടും നൽകാം.",
            "സംഭവിച്ചതിന്റെ തെളിവുകൾ സൂക്ഷിക്കുക: മെഡിക്കൽ രേഖകൾ, ഫോട്ടോകൾ, സന്ദേശങ്ങൾ, സാക്ഷികളുടെ പേരുകൾ.",
            "അടുത്തുള്ള പോലീസ് സ്റ്റേഷനിൽ രേഖാമൂലമുള്ള പരാതി നൽകാം; നിങ്ങളുടെ ജില്ലയിലെ പ്രൊട്ടക്ഷൻ ഓഫീസർ/സേവന ദാതാവിനും അത് സ്വീകരിക്കാം.",
            "നിങ്ങളുടെ സാഹചര്യത്തിൽ ലഭ്യമായ പരിഹാരങ്ങളെക്കുറിച്ച് യോഗ്യനായ അഭിഭാഷകനുമായി സംസാരിക്കുക.",
        ),
        "threat_harassment": (
            "ഇപ്പോൾ സുരക്ഷിതമല്ലെന്ന് തോന്നുന്നുവെങ്കിൽ, ആദ്യം മുകളിലുള്ള അടിയന്തര നമ്പറുകളിൽ വിളിക്കുക.",
            "തെളിവുകൾ കിട്ടിയ അതേ രൂപത്തിൽ സൂക്ഷിക്കുക — ഒന്നും ഇല്ലാതാക്കരുത്. കോൾ ലോഗുകൾ, സന്ദേശങ്ങളുടെ സ്ക്രീൻഷോട്ടുകൾ, റെക്കോർഡിംഗുകൾ, തീയതി-സമയം, കോൾ വരുന്ന നമ്പർ എന്നിവ സൂക്ഷിക്കുക.",
            "അധികാരപരിധിയിലുള്ള പോലീസ് സ്റ്റേഷനിൽ രേഖാമൂലമുള്ള പരാതി നൽകി, രസീത് നമ്പർ സഹിതം സ്വീകരിച്ച പകർപ്പ് കൈവശം വയ്ക്കുക.",
            "പോലീസ് സ്റ്റേഷൻ പരാതി രജിസ്റ്റർ ചെയ്യുന്നില്ലെങ്കിൽ, അതേ പരാതി രേഖാമൂലം പോലീസ് സൂപ്രണ്ടിന് അയയ്ക്കാം.",
        ),
        "cyber_financial_fraud": (
            "ഇടപാടിനെക്കുറിച്ച് ഉടൻ നിങ്ങളുടെ ബാങ്കിനെ അറിയിക്കുകയും അക്കൗണ്ട്/കാർഡ് ബ്ലോക്ക് ചെയ്യാൻ രേഖാമൂലം ആവശ്യപ്പെടുകയും ചെയ്യുക — തട്ടിപ്പ് എത്ര വേഗം റിപ്പോർട്ട് ചെയ്യുന്നുവോ, പണം തടയാനുള്ള സാധ്യത അത്രയും കൂടും.",
            "തെളിവുകൾ സൂക്ഷിക്കുക: ഇടപാട് ഐഡി/UTR നമ്പർ, ബാങ്ക് SMS അലേർട്ടുകൾ, സ്റ്റേറ്റ്‌മെന്റുകൾ, സ്ക്രീൻഷോട്ടുകൾ, ബന്ധപ്പെട്ട വ്യക്തിയുമായുള്ള ചാറ്റ് അല്ലെങ്കിൽ കോൾ രേഖകൾ.",
            "ദേശീയ സൈബർ ക്രൈം റിപ്പോർട്ടിംഗ് പോർട്ടലിലും അടുത്തുള്ള സൈബർ സെൽ/പോലീസ് സ്റ്റേഷനിലും പരാതി നൽകി, അക്നോളജ്‌മെന്റ് നമ്പർ സൂക്ഷിക്കുക.",
            "പണം തിരിച്ചുപിടിക്കുന്നതിനെക്കുറിച്ചും നിങ്ങളുടെ വസ്തുതകൾക്ക് ബാധകമായ വ്യവസ്ഥകളെക്കുറിച്ചും യോഗ്യനായ അഭിഭാഷകനുമായി സംസാരിക്കുക.",
        ),
    },
    "punjabi": {
        "domestic_violence": (
            "ਜੇ ਤੁਸੀਂ ਤੁਰੰਤ ਖ਼ਤਰੇ ਵਿੱਚ ਹੋ, ਤਾਂ ਪਹਿਲਾਂ ਉੱਪਰ ਦਿੱਤੇ ਐਮਰਜੈਂਸੀ ਨੰਬਰਾਂ ਉੱਤੇ ਕਾਲ ਕਰੋ — ਸ਼ਿਕਾਇਤ ਬਾਅਦ ਵਿੱਚ ਵੀ ਹੋ ਸਕਦੀ ਹੈ।",
            "ਜੋ ਹੋਇਆ ਉਸਦਾ ਸਬੂਤ ਸੰਭਾਲੋ: ਮੈਡੀਕਲ ਰਿਕਾਰਡ, ਤਸਵੀਰਾਂ, ਸੁਨੇਹੇ ਅਤੇ ਗਵਾਹਾਂ ਦੇ ਨਾਮ।",
            "ਲਿਖਤੀ ਸ਼ਿਕਾਇਤ ਨੇੜਲੇ ਪੁਲਿਸ ਥਾਣੇ ਵਿੱਚ ਦਿੱਤੀ ਜਾ ਸਕਦੀ ਹੈ; ਤੁਹਾਡੇ ਜ਼ਿਲ੍ਹੇ ਦਾ ਪ੍ਰੋਟੈਕਸ਼ਨ ਅਫ਼ਸਰ/ਸੇਵਾ ਪ੍ਰਦਾਤਾ ਵੀ ਇਹ ਲੈ ਸਕਦਾ ਹੈ।",
            "ਤੁਹਾਡੀ ਸਥਿਤੀ ਵਿੱਚ ਉਪਲਬਧ ਰਾਹਤਾਂ ਬਾਰੇ ਕਿਸੇ ਯੋਗ ਵਕੀਲ ਨਾਲ ਗੱਲ ਕਰੋ।",
        ),
        "threat_harassment": (
            "ਜੇ ਤੁਸੀਂ ਹੁਣ ਅਸੁਰੱਖਿਅਤ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ, ਤਾਂ ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਉੱਪਰ ਦਿੱਤੇ ਐਮਰਜੈਂਸੀ ਨੰਬਰਾਂ ਉੱਤੇ ਕਾਲ ਕਰੋ।",
            "ਸਬੂਤ ਜਿਵੇਂ ਮਿਲੇ ਉਵੇਂ ਸੰਭਾਲੋ — ਕੁਝ ਵੀ ਨਾ ਮਿਟਾਓ। ਕਾਲ ਲੌਗ, ਸੁਨੇਹਿਆਂ ਦੇ ਸਕ੍ਰੀਨਸ਼ਾਟ, ਰਿਕਾਰਡਿੰਗ, ਮਿਤੀ-ਸਮਾਂ ਅਤੇ ਜਿਸ ਨੰਬਰ ਤੋਂ ਕਾਲ ਆ ਰਹੀ ਹੈ, ਉਹ ਸੰਭਾਲੋ।",
            "ਅਧਿਕਾਰ ਖੇਤਰ ਵਾਲੇ ਪੁਲਿਸ ਥਾਣੇ ਵਿੱਚ ਲਿਖਤੀ ਸ਼ਿਕਾਇਤ ਦਿਓ ਅਤੇ ਰਸੀਦ ਨੰਬਰ ਸਮੇਤ ਪ੍ਰਵਾਨਿਤ ਕਾਪੀ ਆਪਣੇ ਕੋਲ ਰੱਖੋ।",
            "ਜੇ ਥਾਣਾ ਸ਼ਿਕਾਇਤ ਦਰਜ ਨਾ ਕਰੇ, ਤਾਂ ਉਹੀ ਸ਼ਿਕਾਇਤ ਲਿਖਤੀ ਰੂਪ ਵਿੱਚ ਪੁਲਿਸ ਸੁਪਰਡੈਂਟ ਨੂੰ ਭੇਜੀ ਜਾ ਸਕਦੀ ਹੈ।",
        ),
        "cyber_financial_fraud": (
            "ਲੈਣ-ਦੇਣ ਦੀ ਜਾਣਕਾਰੀ ਤੁਰੰਤ ਆਪਣੇ ਬੈਂਕ ਨੂੰ ਦਿਓ ਅਤੇ ਲਿਖਤੀ ਰੂਪ ਵਿੱਚ ਖਾਤਾ/ਕਾਰਡ ਬਲਾਕ ਕਰਨ ਲਈ ਕਹੋ — ਧੋਖਾਧੜੀ ਜਿੰਨੀ ਜਲਦੀ ਦੱਸੀ ਜਾਵੇ, ਪੈਸੇ ਰੁਕਣ ਦੀ ਸੰਭਾਵਨਾ ਓਨੀ ਵੱਧ ਹੈ।",
            "ਸਬੂਤ ਸੰਭਾਲੋ: ਟ੍ਰਾਂਜ਼ੈਕਸ਼ਨ ਆਈਡੀ/UTR ਨੰਬਰ, ਬੈਂਕ ਦੇ SMS ਅਲਰਟ, ਸਟੇਟਮੈਂਟ, ਸਕ੍ਰੀਨਸ਼ਾਟ ਅਤੇ ਸਬੰਧਤ ਵਿਅਕਤੀ ਨਾਲ ਹੋਈ ਚੈਟ ਜਾਂ ਕਾਲ ਦਾ ਰਿਕਾਰਡ।",
            "ਨੈਸ਼ਨਲ ਸਾਈਬਰ ਕ੍ਰਾਈਮ ਰਿਪੋਰਟਿੰਗ ਪੋਰਟਲ ਉੱਤੇ ਅਤੇ ਨੇੜਲੇ ਸਾਈਬਰ ਸੈੱਲ/ਪੁਲਿਸ ਥਾਣੇ ਵਿੱਚ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ, ਅਤੇ ਪ੍ਰਾਪਤੀ ਨੰਬਰ ਸੰਭਾਲੋ।",
            "ਪੈਸੇ ਦੀ ਵਸੂਲੀ ਅਤੇ ਤੁਹਾਡੇ ਤੱਥਾਂ ਉੱਤੇ ਲਾਗੂ ਹੋਣ ਵਾਲੀਆਂ ਵਿਵਸਥਾਵਾਂ ਬਾਰੇ ਕਿਸੇ ਯੋਗ ਵਕੀਲ ਨਾਲ ਗੱਲ ਕਰੋ।",
        ),
    },
    "odia": {
        "domestic_violence": (
            "ଆପଣ ତତ୍‌କ୍ଷଣାତ୍ ବିପଦରେ ଥିଲେ, ପ୍ରଥମେ ଉପରୋକ୍ତ ଜରୁରୀକାଳୀନ ନମ୍ବରକୁ ଫୋନ୍ କରନ୍ତୁ — ଅଭିଯୋଗ ପରେ ମଧ୍ୟ କରାଯାଇପାରିବ।",
            "ଯାହା ଘଟିଛି ତାହାର ପ୍ରମାଣ ସୁରକ୍ଷିତ ରଖନ୍ତୁ: ଡାକ୍ତରୀ ରେକର୍ଡ, ଫଟୋ, ବାର୍ତ୍ତା ଏବଂ ସାକ୍ଷୀଙ୍କ ନାମ।",
            "ନିକଟସ୍ଥ ପୋଲିସ ଥାନାରେ ଲିଖିତ ଅଭିଯୋଗ ଦିଆଯାଇପାରିବ; ଆପଣଙ୍କ ଜିଲ୍ଲାର ସୁରକ୍ଷା ଅଧିକାରୀ/ସେବା ପ୍ରଦାନକାରୀ ମଧ୍ୟ ତାହା ଗ୍ରହଣ କରିପାରିବେ।",
            "ଆପଣଙ୍କ ପରିସ୍ଥିତିରେ ଉପଲବ୍ଧ ପ୍ରତିକାର ବିଷୟରେ ଜଣେ ଯୋଗ୍ୟ ଓକିଲଙ୍କ ସହ କଥା ହୁଅନ୍ତୁ।",
        ),
        "threat_harassment": (
            "ଆପଣ ବର୍ତ୍ତମାନ ଅସୁରକ୍ଷିତ ଅନୁଭବ କରୁଥିଲେ, ସର୍ବପ୍ରଥମେ ଉପରୋକ୍ତ ଜରୁରୀକାଳୀନ ନମ୍ବରକୁ ଫୋନ୍ କରନ୍ତୁ।",
            "ପ୍ରମାଣକୁ ଯେପରି ମିଳିଛି ସେହିପରି ରଖନ୍ତୁ — କିଛି ବି ଡିଲିଟ୍ କରନ୍ତୁ ନାହିଁ। କଲ୍ ଲଗ୍, ବାର୍ତ୍ତାର ସ୍କ୍ରିନସଟ୍, ରେକର୍ଡିଂ, ତାରିଖ-ସମୟ ଏବଂ ଯେଉଁ ନମ୍ବରରୁ କଲ୍ ଆସୁଛି ତାହା ରଖନ୍ତୁ।",
            "ଅଧିକାର ପରିସରର ପୋଲିସ ଥାନାରେ ଲିଖିତ ଅଭିଯୋଗ ଦିଅନ୍ତୁ ଏବଂ ରସିଦ ନମ୍ବର ସହିତ ଗୃହୀତ ନକଲ ନିଜ ପାଖରେ ରଖନ୍ତୁ।",
            "ଥାନା ଅଭିଯୋଗ ପଞ୍ଜୀକୃତ ନକଲେ, ସେହି ଅଭିଯୋଗ ଲିଖିତ ଭାବେ ପୋଲିସ ଅଧୀକ୍ଷକଙ୍କୁ ପଠାଯାଇପାରିବ।",
        ),
        "cyber_financial_fraud": (
            "କାରବାର ବିଷୟରେ ତୁରନ୍ତ ଆପଣଙ୍କ ବ୍ୟାଙ୍କକୁ ଜଣାନ୍ତୁ ଏବଂ ଲିଖିତ ଭାବେ ଖାତା/କାର୍ଡ ବ୍ଲକ୍ କରିବାକୁ କୁହନ୍ତୁ — ପ୍ରତାରଣା ଯେତେ ଶୀଘ୍ର ରିପୋର୍ଟ ହେବ, ଟଙ୍କା ଅଟକିବାର ସମ୍ଭାବନା ସେତେ ଅଧିକ।",
            "ପ୍ରମାଣ ସୁରକ୍ଷିତ ରଖନ୍ତୁ: ଟ୍ରାନଜାକ୍ସନ୍ ଆଇଡି/UTR ନମ୍ବର, ବ୍ୟାଙ୍କର SMS ଆଲର୍ଟ, ଷ୍ଟେଟମେଣ୍ଟ, ସ୍କ୍ରିନସଟ୍ ଏବଂ ସମ୍ପୃକ୍ତ ବ୍ୟକ୍ତିଙ୍କ ସହ ହୋଇଥିବା ଚାଟ୍ କିମ୍ବା କଲ୍ ରେକର୍ଡ।",
            "ଜାତୀୟ ସାଇବର କ୍ରାଇମ୍ ରିପୋର୍ଟିଂ ପୋର୍ଟାଲରେ ଏବଂ ନିକଟସ୍ଥ ସାଇବର ସେଲ୍/ପୋଲିସ ଥାନାରେ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ, ଏବଂ ପ୍ରାପ୍ତି ନମ୍ବର ରଖନ୍ତୁ।",
            "ଟଙ୍କା ଫେରସ୍ତ ଏବଂ ଆପଣଙ୍କ ତଥ୍ୟ ଉପରେ ଲାଗୁ ହେଉଥିବା ବ୍ୟବସ୍ଥା ବିଷୟରେ ଜଣେ ଯୋଗ୍ୟ ଓକିଲଙ୍କ ସହ କଥା ହୁଅନ୍ତୁ।",
        ),
    },
    "urdu": {
        "domestic_violence": (
            "اگر آپ فوری خطرے میں ہیں تو پہلے اوپر دیے گئے ایمرجنسی نمبروں پر کال کریں — شکایت بعد میں بھی درج کرائی جا سکتی ہے۔",
            "جو کچھ ہوا اس کا ثبوت محفوظ رکھیں: طبی ریکارڈ، تصاویر، پیغامات اور گواہوں کے نام۔",
            "تحریری شکایت قریبی پولیس اسٹیشن میں دی جا سکتی ہے؛ آپ کے ضلع کا پروٹیکشن آفیسر/سروس فراہم کنندہ بھی اسے وصول کر سکتا ہے۔",
            "اپنی صورتحال میں دستیاب ریلیف کے بارے میں کسی مستند وکیل سے بات کریں۔",
        ),
        "threat_harassment": (
            "اگر آپ اس وقت غیر محفوظ محسوس کر رہے ہیں تو سب سے پہلے اوپر دیے گئے ایمرجنسی نمبروں پر کال کریں۔",
            "ثبوت جیسے ملے ویسے ہی محفوظ رکھیں — کچھ بھی حذف نہ کریں۔ کال لاگ، پیغامات کے اسکرین شاٹ، ریکارڈنگ، تاریخ و وقت اور جس نمبر سے کالیں آ رہی ہیں وہ محفوظ رکھیں۔",
            "متعلقہ دائرہ اختیار کے پولیس اسٹیشن میں تحریری شکایت دیں اور رسید نمبر سمیت تصدیق شدہ نقل اپنے پاس رکھیں۔",
            "اگر پولیس اسٹیشن شکایت درج نہ کرے تو وہی شکایت تحریری طور پر ایس پی کو بھیجی جا سکتی ہے۔",
        ),
        "cyber_financial_fraud": (
            "لین دین کی اطلاع فوراً اپنے بینک کو دیں اور تحریری طور پر اکاؤنٹ/کارڈ بلاک کرنے کو کہیں — فراڈ جتنی جلدی رپورٹ ہوگا، رقم رکنے کے امکانات اتنے زیادہ ہوں گے۔",
            "ثبوت محفوظ رکھیں: ٹرانزیکشن آئی ڈی/UTR نمبر، بینک کے SMS الرٹ، اسٹیٹمنٹ، اسکرین شاٹ اور متعلقہ شخص سے ہونے والی چیٹ یا کال کا ریکارڈ۔",
            "نیشنل سائبر کرائم رپورٹنگ پورٹل پر اور قریبی سائبر سیل/پولیس اسٹیشن میں شکایت درج کرائیں، اور رسید نمبر محفوظ رکھیں۔",
            "رقم کی واپسی اور آپ کے حقائق پر لاگو ہونے والی دفعات کے بارے میں کسی مستند وکیل سے بات کریں۔",
        ),
    },
}

_HEADINGS: dict[str, str] = {
    "tamil": "இதற்கிடையில், நீங்கள் இப்போது செய்யக்கூடியவை",
    "telugu": "ఈలోగా, మీరు ఇప్పుడు చేయగలిగినవి",
    "kannada": "ಈ ಮಧ್ಯೆ, ನೀವು ಈಗ ಮಾಡಬಹುದಾದದ್ದು",
    "malayalam": "അതിനിടെ, നിങ്ങൾക്ക് ഇപ്പോൾ ചെയ്യാവുന്നത്",
    "punjabi": "ਇਸ ਦੌਰਾਨ, ਤੁਸੀਂ ਹੁਣ ਇਹ ਕਰ ਸਕਦੇ ਹੋ",
    "odia": "ଏହି ସମୟରେ, ଆପଣ ବର୍ତ୍ତମାନ ଏହା କରିପାରିବେ",
    "urdu": "اس دوران، آپ ابھی یہ کر سکتے ہیں",
    "english": "In the meantime, here is what you can do right now",
    "hindi": "इस बीच, आप अभी ये कदम उठा सकते हैं",
    "hinglish": "Tab tak, aap abhi ye kar sakte hain",
    "marathi": "दरम्यान, तुम्ही आत्ता हे करू शकता",
    "gujarati": "દરમિયાન, તમે અત્યારે આ કરી શકો છો",
    "bengali": "ইতিমধ্যে, আপনি এখনই যা করতে পারেন",
    # Added with `_GENERIC_NEXT_STEPS` below. These languages have NO entry in
    # `_STEPS`/`_CHANNEL_LABELS`/`_SOURCE_NOTES`/`_DRAFT_OFFERS`, so
    # `actionable_guidance` (the urgent-situation block) falls back to English
    # for the WHOLE block for them -- see the `resolved` guard there.
    "nepali": "यसै बीचमा, तपाईंले अहिले गर्न सक्ने कुराहरू",
    "maithili": "एहि बीच, अहाँ एखन ई सभ कऽ सकैत छी",
    "sanskrit": "एतावता, भवान् इदानीं किं कर्तुं शक्नोति",
    "konkani": "ह्या मदीं, तुमी आतां हें करूं येता",
    "dogri": "इस बिच्च, तुस हुन एह् करी सकदे ओ",
    "assamese": "ইতিমধ্যে, আপুনি এতিয়া যি কৰিব পাৰে",
    "sindhi": "هن دوران، توهان هاڻي هي ڪري سگهو ٿا",
}
_CHANNEL_LABELS: dict[str, str] = {
    "tamil": "அதிகாரப்பூர்வ உதவி எண்கள்",
    "telugu": "అధికారిక హెల్ప్‌లైన్‌లు",
    "kannada": "ಅಧಿಕೃತ ಸಹಾಯವಾಣಿಗಳು",
    "malayalam": "ഔദ്യോഗിക ഹെൽപ്‌ലൈനുകൾ",
    "punjabi": "ਸਰਕਾਰੀ ਹੈਲਪਲਾਈਨਾਂ",
    "odia": "ସରକାରୀ ହେଲ୍ପଲାଇନ",
    "urdu": "سرکاری ہیلپ لائنز",
    "english": "Official helplines",
    "hindi": "आधिकारिक हेल्पलाइन",
    "hinglish": "Official helplines",
    "marathi": "अधिकृत हेल्पलाइन",
    "gujarati": "સત્તાવાર હેલ્પલાઇન",
    "bengali": "সরকারি হেল্পলাইন",
}
_SOURCE_NOTES: dict[str, str] = {
    "marathi": (
        "हे भारत सरकारचे सार्वजनिक हेल्पलाइन क्रमांक व राष्ट्रीय तक्रार पोर्टल आहे, कायद्याचा अर्थ नाही. तुमच्या विशिष्ट तथ्यांवर कायदा काय म्हणतो यासाठी कृपया पात्र वकिलाचा सल्ला घ्या."
    ),
    "gujarati": (
        "આ ભારત સરકારના જાહેર હેલ્પલાઇન નંબર અને રાષ્ટ્રીય રિપોર્ટિંગ પોર્ટલ છે, કાયદાનું અર્થઘટન નથી. તમારી ચોક્કસ હકીકતો પર કાયદો શું કહે છે તે માટે કૃપા કરીને લાયક વકીલની સલાહ લો."
    ),
    "bengali": (
        "এগুলি ভারত সরকারের সরকারি হেল্পলাইন নম্বর ও জাতীয় রিপোর্টিং পোর্টাল, আইনের ব্যাখ্যা নয়। আপনার নির্দিষ্ট ঘটনার ক্ষেত্রে আইন কী বলে তার জন্য অনুগ্রহ করে যোগ্য আইনজীবীর পরামর্শ নিন।"
    ),
    "tamil": (
        "இவை இந்திய அரசின் பொது உதவி எண்கள் மற்றும் தேசிய புகார் இணையதளம், சட்ட விளக்கம் அல்ல. உங்கள் குறிப்பிட்ட நிகழ்வுக்குச் சட்டம் என்ன கூறுகிறது என்பதற்குத் தகுதியான வழக்கறிஞரை அணுகவும்."
    ),
    "telugu": (
        "ఇవి భారత ప్రభుత్వ ప్రజా హెల్ప్‌లైన్ నంబర్లు మరియు జాతీయ రిపోర్టింగ్ పోర్టల్, చట్ట వ్యాఖ్యానం కాదు. మీ నిర్దిష్ట వాస్తవాలపై చట్టం ఏమి చెబుతుందో తెలుసుకోవడానికి అర్హతగల న్యాయవాదిని సంప్రదించండి."
    ),
    "kannada": (
        "ಇವು ಭಾರತ ಸರ್ಕಾರದ ಸಾರ್ವಜನಿಕ ಸಹಾಯವಾಣಿ ಸಂಖ್ಯೆಗಳು ಮತ್ತು ರಾಷ್ಟ್ರೀಯ ವರದಿ ಪೋರ್ಟಲ್, ಕಾನೂನಿನ ವ್ಯಾಖ್ಯಾನವಲ್ಲ. ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಸಂಗತಿಗಳ ಬಗ್ಗೆ ಕಾನೂನು ಏನು ಹೇಳುತ್ತದೆ ಎಂಬುದಕ್ಕೆ ಅರ್ಹ ವಕೀಲರನ್ನು ಸಂಪರ್ಕಿಸಿ."
    ),
    "malayalam": (
        "ഇവ ഇന്ത്യാ ഗവൺമെന്റിന്റെ പൊതു ഹെൽപ്‌ലൈൻ നമ്പറുകളും ദേശീയ റിപ്പോർട്ടിംഗ് പോർട്ടലുമാണ്, നിയമവ്യാഖ്യാനമല്ല. നിങ്ങളുടെ പ്രത്യേക വസ്തുതകളിൽ നിയമം എന്തു പറയുന്നു എന്നതിന് യോഗ്യനായ അഭിഭാഷകനെ സമീപിക്കുക."
    ),
    "punjabi": (
        "ਇਹ ਭਾਰਤ ਸਰਕਾਰ ਦੇ ਜਨਤਕ ਹੈਲਪਲਾਈਨ ਨੰਬਰ ਅਤੇ ਰਾਸ਼ਟਰੀ ਰਿਪੋਰਟਿੰਗ ਪੋਰਟਲ ਹਨ, ਕਾਨੂੰਨ ਦੀ ਵਿਆਖਿਆ ਨਹੀਂ। ਤੁਹਾਡੇ ਖਾਸ ਤੱਥਾਂ ਉੱਤੇ ਕਾਨੂੰਨ ਕੀ ਕਹਿੰਦਾ ਹੈ, ਇਸ ਲਈ ਕਿਸੇ ਯੋਗ ਵਕੀਲ ਦੀ ਸਲਾਹ ਲਓ।"
    ),
    "odia": (
        "ଏଗୁଡ଼ିକ ଭାରତ ସରକାରଙ୍କ ସାର୍ବଜନୀନ ହେଲ୍ପଲାଇନ ନମ୍ବର ଏବଂ ଜାତୀୟ ରିପୋର୍ଟିଂ ପୋର୍ଟାଲ, ଆଇନର ବ୍ୟାଖ୍ୟା ନୁହେଁ। ଆପଣଙ୍କ ନିର୍ଦ୍ଦିଷ୍ଟ ତଥ୍ୟ ଉପରେ ଆଇନ କ'ଣ କହେ, ସେଥିପାଇଁ ଜଣେ ଯୋଗ୍ୟ ଓକିଲଙ୍କ ପରାମର୍ଶ ନିଅନ୍ତୁ।"
    ),
    "urdu": (
        "یہ حکومتِ ہند کے عوامی ہیلپ لائن نمبر اور قومی رپورٹنگ پورٹل ہیں، قانون کی تشریح نہیں۔ آپ کے مخصوص حقائق پر قانون کیا کہتا ہے، اس کے لیے کسی مستند وکیل سے مشورہ کریں۔"
    ),
    "english": (
        "These are Government of India public helpline numbers and the national reporting portal, not an "
        "interpretation of the law. For what the law says about your specific facts, please consult a "
        "qualified advocate."
    ),
    "hindi": (
        "ये भारत सरकार की सार्वजनिक हेल्पलाइन संख्याएँ और राष्ट्रीय रिपोर्टिंग पोर्टल हैं, कानून की व्याख्या नहीं। "
        "आपके विशिष्ट तथ्यों पर कानून क्या कहता है, इसके लिए कृपया किसी योग्य अधिवक्ता से परामर्श करें।"
    ),
    "hinglish": (
        "Ye Government of India ke public helpline numbers aur national reporting portal hain, law ki "
        "interpretation nahi. Aapke specific facts par law kya kehta hai, iske liye kisi qualified advocate "
        "se consult karein."
    ),
}
# `{template}` names the document in the user's own language; `{command}` is
# always the ENGLISH template name, because that is what `DraftIntentDetector`
# scores most reliably -- telling a Hindi speaker to type a phrase the
# detector might not match would be worse than making no offer at all.
_DRAFT_OFFERS: dict[str, str] = {
    "english": 'I can also prepare a {template} draft for you — just say "draft a {command}".',
    "hindi": 'मैं आपके लिए {template} का मसौदा भी तैयार कर सकता हूँ — बस "draft a {command}" कहें।',
    "hinglish": 'Main aapke liye {template} ka draft bhi bana sakta hoon — bas "draft a {command}" kahein.',
    "marathi": 'मी तुमच्यासाठी {template} चा मसुदा देखील तयार करू शकतो — फक्त "draft a {command}" म्हणा.',
    "gujarati": 'હું તમારા માટે {template} નો ડ્રાફ્ટ પણ તૈયાર કરી શકું છું — ફક્ત "draft a {command}" કહો.',
    "bengali": 'আমি আপনার জন্য {template} খসড়াও তৈরি করতে পারি — শুধু "draft a {command}" বলুন।',
    # These 7 close the gap with `_STEPS`/`_HEADINGS`/`_CHANNEL_LABELS`/
    # `_SOURCE_NOTES`, which already cover them -- without an entry here, a
    # Tamil/Telugu/Kannada/Malayalam/Punjabi/Odia/Urdu speaker got every other
    # line of `actionable_guidance` in their own language except this one
    # trailing sentence, which silently fell back to English mid-block (the
    # "mixed scripts" failure mode from qa-40q-multilingual-20260921 BUG-01/
    # BUG-02). Same translation-provenance caveat as the rest of this module.
    "kannada": 'ನಾನು ನಿಮಗಾಗಿ {template} ಡ್ರಾಫ್ಟ್ ಅನ್ನು ಸಹ ಸಿದ್ಧಪಡಿಸಬಲ್ಲೆ — ಬಸ "draft a {command}" ಎಂದು ಹೇಳಿ.',
    "malayalam": 'എനിക്ക് നിങ്ങൾക്കായി {template} ഡ്രാഫ്റ്റും തയ്യാറാക്കാം — "draft a {command}" എന്ന് പറഞ്ഞാൽ മതി.',
    "odia": 'ମୁଁ ଆପଣଙ୍କ ପାଇଁ {template} ର ଡ୍ରାଫ୍ଟ ମଧ୍ୟ ପ୍ରସ୍ତୁତ କରିପାରିବି — କେବଳ "draft a {command}" କୁହନ୍ତୁ।',
    "punjabi": 'ਮੈਂ ਤੁਹਾਡੇ ਲਈ {template} ਦਾ ਡਰਾਫਟ ਵੀ ਤਿਆਰ ਕਰ ਸਕਦਾ ਹਾਂ — ਬਸ "draft a {command}" ਕਹੋ।',
    "tamil": 'நான் உங்களுக்காக {template} வரைவையும் தயாரிக்க முடியும் — "draft a {command}" என்று சொல்லுங்கள்.',
    "telugu": 'నేను మీ కోసం {template} డ్రాఫ్ట్‌ను కూడా సిద్ధం చేయగలను — "draft a {command}" అని చెప్పండి.',
    "urdu": 'میں آپ کے لیے {template} کا ڈرافٹ بھی تیار کر سکتا ہوں — بس "draft a {command}" کہیں۔',
}


def _localized(table: dict[str, str], language: str | None) -> str:
    return table.get((language or "english").strip().lower(), table["english"])


def detect_category(question: str) -> GuidanceCategory | None:
    """The urgency category `question` falls into, or `None` for an ordinary
    informational question that needs no safety escalation."""
    for category in _CATEGORIES:
        if category.pattern.search(question or ""):
            return category
    return None


# Confirmed live: an ORDINARY informational question that trips the strict-RAG
# refusal ("BNS Section 12 kya hai", "how to send a legal notice", "which
# section of the Hindu Marriage Act covers maintenance") -- none of which is
# an urgency category above -- got the bare refusal and stopped there, with
# no path forward at all. The three `_CATEGORIES` above intentionally don't
# fit this shape (there is no emergency helpline for "which section covers
# X"), so this is a second, distinct, non-urgent fallback: concrete things
# the user can try next, not government channels.
#
# Coverage matches `_HEADINGS` deliberately (all 13 languages, not just
# english/hindi/hinglish): `generic_next_steps_guidance` below builds its
# heading from `_HEADINGS` and its body from this dict, so if the two tables
# ever cover a different language set, a language present in one but not the
# other gets a native-script heading over English-fallback body text (or vice
# versa) -- a same-block script mix, not a clean single-language fallback.
# That was exactly qa-40q-multilingual-20260921's BUG-01/BUG-02: the refusal
# line above was correctly localized (`NO_VERIFIED_CONTEXT_MESSAGES` covers
# all 22 scheduled languages) while this block silently reverted to English
# for every language beyond the original three, producing a native-refusal +
# English-guidance mix in the same reply. Any language still absent from both
# tables together (the 11 lower-resource ones neither table covers) falls
# back to English consistently across the whole block instead -- English, not
# mixed, which is the same known/documented degradation the rest of this
# module already accepts elsewhere. Same translation-provenance caveat as the
# rest of this module: content beyond hindi/hinglish is assistant-authored
# and not yet native-speaker reviewed.
_GENERIC_NEXT_STEPS: dict[str, tuple[str, ...]] = {
    "english": (
        "Name the exact Act and section number if you know it (e.g. \"Section 100 of the Bharatiya Nyaya Sanhita\") — an exact citation searches very differently from a topic description.",
        "The provision or Act you're asking about may genuinely not be in this Knowledge Base yet, rather than a phrasing problem — try a nearby, related question to check.",
        "If you have the relevant document yourself, uploading it lets me answer from it directly.",
        "For what the law actually says on your specific facts, a qualified advocate can confirm what a search here cannot.",
    ),
    "hindi": (
        "अगर आपको पता है तो सटीक अधिनियम और धारा संख्या बताएं (जैसे \"भारतीय न्याय संहिता की धारा 100\") — सटीक उद्धरण, विषय के सामान्य विवरण से बिल्कुल अलग तरीके से खोजा जाता है।",
        "हो सकता है आप जिस प्रावधान या अधिनियम के बारे में पूछ रहे हैं वह अभी इस Knowledge Base में हो ही नहीं — यह शब्दों की समस्या नहीं भी हो सकती; जांचने के लिए कोई नज़दीकी, संबंधित सवाल आज़माएं।",
        "अगर संबंधित दस्तावेज़ आपके पास है, तो उसे अपलोड करने पर मैं सीधे उसी से जवाब दे सकता हूँ।",
        "आपके विशिष्ट तथ्यों पर कानून वास्तव में क्या कहता है, यह किसी योग्य अधिवक्ता से ही स्पष्ट होगा।",
    ),
    "hinglish": (
        "Agar pata ho to exact Act aur section number batayein (jaise \"Bharatiya Nyaya Sanhita ki Section 100\") — exact citation, topic ke general description se bilkul alag tarike se search hota hai.",
        "Ho sakta hai jis provision ya Act ke baare mein aap pooch rahe hain woh abhi is Knowledge Base mein ho hi nahi — ye sirf phrasing ka issue na ho; check karne ke liye koi nazdeeki, related sawaal try karein.",
        "Agar relevant document aapke paas hai, to use upload karne par main seedha usi se jawab de sakta hoon.",
        "Aapke specific facts par law asal mein kya kehta hai, ye kisi qualified advocate se hi confirm hoga.",
    ),
    "marathi": (
        "तुम्हाला माहीत असल्यास नेमका कायदा आणि कलम क्रमांक सांगा (उदा. \"भारतीय न्याय संहितेचे कलम 100\") — नेमके उद्धरण, विषयाच्या सर्वसाधारण वर्णनापेक्षा पूर्णपणे वेगळ्या पद्धतीने शोधले जाते.",
        "तुम्ही विचारत असलेली तरतूद किंवा कायदा या Knowledge Base मध्ये अजून खरोखरच नसू शकतो, शब्दरचनेची अडचण नसूही — पडताळण्यासाठी जवळचा, संबंधित प्रश्न विचारून पहा.",
        "संबंधित दस्तऐवज तुमच्याकडे असल्यास, तो अपलोड केल्यास मी थेट त्यावरून उत्तर देऊ शकतो.",
        "तुमच्या विशिष्ट तथ्यांवर कायदा प्रत्यक्षात काय सांगतो, हे फक्त पात्र वकीलच स्पष्ट करू शकतील, इथला शोध नाही.",
    ),
    "gujarati": (
        "જો તમને ખબર હોય તો ચોક્કસ અધિનિયમ અને કલમ નંબર જણાવો (દા.ત. \"ભારતીય ન્યાય સંહિતાની કલમ 100\") — ચોક્કસ ટાંકણ, વિષયના સામાન્ય વર્ણન કરતાં તદ્દન અલગ રીતે શોધાય છે.",
        "તમે જે જોગવાઈ કે અધિનિયમ વિશે પૂછી રહ્યા છો તે હજુ આ Knowledge Base માં ન પણ હોય, એ શબ્દરચનાની સમસ્યા ન પણ હોય — ચકાસવા માટે નજીકનો, સંબંધિત પ્રશ્ન અજમાવો.",
        "જો સંબંધિત દસ્તાવેજ તમારી પાસે હોય, તો તેને અપલોડ કરવાથી હું સીધો તેમાંથી જવાબ આપી શકું છું.",
        "તમારી ચોક્કસ હકીકતો પર કાયદો ખરેખર શું કહે છે, તે ફક્ત લાયક વકીલ જ સ્પષ્ટ કરી શકશે, અહીંની શોધ નહીં.",
    ),
    "bengali": (
        "যদি জানা থাকে তবে সঠিক আইন ও ধারা নম্বর উল্লেখ করুন (যেমন \"ভারতীয় ন্যায় সংহিতার ধারা 100\") — সঠিক উদ্ধৃতি, বিষয়ের সাধারণ বিবরণ থেকে সম্পূর্ণ ভিন্নভাবে অনুসন্ধান করা হয়।",
        "আপনি যে বিধান বা আইন সম্পর্কে জিজ্ঞাসা করছেন তা সত্যিই এখনও এই Knowledge Base-এ নাও থাকতে পারে, ভাষাগত সমস্যা নাও হতে পারে — যাচাই করতে কাছাকাছি, সম্পর্কিত একটি প্রশ্ন চেষ্টা করুন।",
        "প্রাসঙ্গিক নথি আপনার কাছে থাকলে, তা আপলোড করলে আমি সরাসরি তা থেকে উত্তর দিতে পারি।",
        "আপনার নির্দিষ্ট ঘটনায় আইন আসলে কী বলে, তা একজন যোগ্য আইনজীবীই নিশ্চিত করতে পারবেন, এখানকার অনুসন্ধান নয়।",
    ),
    "kannada": (
        "ನಿಮಗೆ ತಿಳಿದಿದ್ದರೆ ನಿಖರವಾದ ಕಾಯ್ದೆ ಮತ್ತು ಸೆಕ್ಷನ್ ಸಂಖ್ಯೆಯನ್ನು ತಿಳಿಸಿ (ಉದಾ. \"ಭಾರತೀಯ ನ್ಯಾಯ ಸಂಹಿತೆಯ ಸೆಕ್ಷನ್ 100\") — ನಿಖರವಾದ ಉಲ್ಲೇಖವು ವಿಷಯದ ಸಾಮಾನ್ಯ ವಿವರಣೆಗಿಂತ ಸಂಪೂರ್ಣ ಭಿನ್ನವಾಗಿ ಹುಡುಕಲ್ಪಡುತ್ತದೆ.",
        "ನೀವು ಕೇಳುತ್ತಿರುವ ನಿಬಂಧನೆ ಅಥವಾ ಕಾಯ್ದೆ ಈ Knowledge Base ನಲ್ಲಿ ಇನ್ನೂ ನಿಜವಾಗಿಯೂ ಇಲ್ಲದಿರಬಹುದು, ಪದಬಳಕೆಯ ಸಮಸ್ಯೆ ಅಲ್ಲದಿರಬಹುದು — ಪರಿಶೀಲಿಸಲು ಹತ್ತಿರದ, ಸಂಬಂಧಿತ ಪ್ರಶ್ನೆಯನ್ನು ಪ್ರಯತ್ನಿಸಿ.",
        "ಸಂಬಂಧಿತ ದಾಖಲೆ ನಿಮ್ಮ ಬಳಿ ಇದ್ದರೆ, ಅದನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿದರೆ ನಾನು ನೇರವಾಗಿ ಅದರಿಂದಲೇ ಉತ್ತರಿಸಬಹುದು.",
        "ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಸಂಗತಿಗಳ ಮೇಲೆ ಕಾನೂನು ನಿಜವಾಗಿ ಏನು ಹೇಳುತ್ತದೆ ಎಂಬುದನ್ನು ಅರ್ಹ ವಕೀಲರು ಮಾತ್ರ ಖಚಿತಪಡಿಸಬಲ್ಲರು, ಇಲ್ಲಿನ ಹುಡುಕಾಟವಲ್ಲ.",
    ),
    "malayalam": (
        "അറിയാമെങ്കിൽ കൃത്യമായ നിയമവും വകുപ്പ് നമ്പറും പറയുക (ഉദാ. \"ഭാരതീയ ന്യായ സംഹിതയുടെ സെക്ഷൻ 100\") — കൃത്യമായ ഉദ്ധരണി, വിഷയത്തിന്റെ പൊതുവായ വിവരണത്തിൽ നിന്ന് തികച്ചും വ്യത്യസ്തമായാണ് തിരയപ്പെടുന്നത്.",
        "നിങ്ങൾ ചോദിക്കുന്ന വ്യവസ്ഥ അല്ലെങ്കിൽ നിയമം ഈ Knowledge Base-ൽ ഇതുവരെ ഇല്ലായിരിക്കാം, ഇത് പദപ്രയോഗത്തിന്റെ പ്രശ്നമല്ലായിരിക്കാം — പരിശോധിക്കാൻ അടുത്ത ബന്ധപ്പെട്ട ഒരു ചോദ്യം പരീക്ഷിക്കുക.",
        "പ്രസക്തമായ രേഖ നിങ്ങളുടെ പക്കൽ ഉണ്ടെങ്കിൽ, അത് അപ്‌ലോഡ് ചെയ്താൽ എനിക്ക് അതിൽ നിന്ന് നേരിട്ട് ഉത്തരം നൽകാം.",
        "നിങ്ങളുടെ പ്രത്യേക വസ്തുതകളിൽ നിയമം യഥാർത്ഥത്തിൽ എന്താണ് പറയുന്നതെന്ന്, ഇവിടത്തെ തിരച്ചിലിനല്ല, യോഗ്യനായ ഒരു അഭിഭാഷകന് മാത്രമേ സ്ഥിരീകരിക്കാൻ കഴിയൂ.",
    ),
    "odia": (
        "ଆପଣଙ୍କୁ ଜଣା ଥିଲେ ସଠିକ ଆଇନ ଏବଂ ଧାରା ସଂଖ୍ୟା କୁହନ୍ତୁ (ଯଥା \"ଭାରତୀୟ ନ୍ୟାୟ ସଂହିତାର ଧାରା 100\") — ଏକ ସଠିକ ଉଦ୍ଧୃତି, ବିଷୟର ସାଧାରଣ ବର୍ଣ୍ଣନାଠାରୁ ସମ୍ପୂର୍ଣ୍ଣ ଭିନ୍ନ ଭାବେ ସନ୍ଧାନ ହୁଏ।",
        "ଆପଣ ପଚାରୁଥିବା ବ୍ୟବସ୍ଥା କିମ୍ବା ଆଇନ ଏହି Knowledge Base ରେ ପ୍ରକୃତରେ ଏପର୍ଯ୍ୟନ୍ତ ନ ଥାଇପାରେ, ଏହା ଶବ୍ଦ ବ୍ୟବହାରର ସମସ୍ୟା ନ ହୋଇପାରେ — ଯାଞ୍ଚ କରିବାକୁ ଏକ ନିକଟସ୍ଥ, ସମ୍ପର୍କିତ ପ୍ରଶ୍ନ ଚେଷ୍ଟା କରନ୍ତୁ।",
        "ଆପଣଙ୍କ ପାଖରେ ସମ୍ପର୍କିତ ଦଲିଲ ଥିଲେ, ତାହା ଅପଲୋଡ୍ କଲେ ମୁଁ ସିଧାସଳଖ ତାହାରୁ ଉତ୍ତର ଦେଇପାରିବି।",
        "ଆପଣଙ୍କ ନିର୍ଦ୍ଦିଷ୍ଟ ତଥ୍ୟ ଉପରେ ଆଇନ ପ୍ରକୃତରେ କ'ଣ କହେ, ତାହା ଏକ ଯୋଗ୍ୟ ଓକିଲ ହିଁ ସ୍ପଷ୍ଟ କରିପାରିବେ, ଏଠାର ସନ୍ଧାନ ନୁହେଁ।",
    ),
    "punjabi": (
        "ਜੇ ਤੁਹਾਨੂੰ ਪਤਾ ਹੋਵੇ ਤਾਂ ਸਹੀ ਐਕਟ ਅਤੇ ਧਾਰਾ ਨੰਬਰ ਦੱਸੋ (ਜਿਵੇਂ \"ਭਾਰਤੀ ਨਿਆਂ ਸੰਹਿਤਾ ਦੀ ਧਾਰਾ 100\") — ਸਹੀ ਹਵਾਲਾ, ਵਿਸ਼ੇ ਦੇ ਆਮ ਵੇਰਵੇ ਨਾਲੋਂ ਬਿਲਕੁਲ ਵੱਖਰੇ ਢੰਗ ਨਾਲ ਖੋਜਿਆ ਜਾਂਦਾ ਹੈ।",
        "ਤੁਸੀਂ ਜਿਸ ਵਿਵਸਥਾ ਜਾਂ ਐਕਟ ਬਾਰੇ ਪੁੱਛ ਰਹੇ ਹੋ, ਉਹ ਅਜੇ ਇਸ Knowledge Base ਵਿੱਚ ਸੱਚਮੁੱਚ ਨਾ ਵੀ ਹੋਵੇ, ਇਹ ਸ਼ਬਦਾਂ ਦੀ ਸਮੱਸਿਆ ਨਾ ਵੀ ਹੋਵੇ — ਜਾਂਚਣ ਲਈ ਕੋਈ ਨੇੜਲਾ, ਸਬੰਧਤ ਸਵਾਲ ਅਜ਼ਮਾਓ।",
        "ਜੇ ਸਬੰਧਤ ਦਸਤਾਵੇਜ਼ ਤੁਹਾਡੇ ਕੋਲ ਹੈ, ਤਾਂ ਇਸਨੂੰ ਅੱਪਲੋਡ ਕਰਨ ਨਾਲ ਮੈਂ ਸਿੱਧਾ ਉਸ ਤੋਂ ਜਵਾਬ ਦੇ ਸਕਦਾ ਹਾਂ।",
        "ਤੁਹਾਡੇ ਖਾਸ ਤੱਥਾਂ ਉੱਤੇ ਕਾਨੂੰਨ ਅਸਲ ਵਿੱਚ ਕੀ ਕਹਿੰਦਾ ਹੈ, ਇਹ ਕੋਈ ਯੋਗ ਵਕੀਲ ਹੀ ਸਪਸ਼ਟ ਕਰ ਸਕਦਾ ਹੈ, ਇੱਥੋਂ ਦੀ ਖੋਜ ਨਹੀਂ।",
    ),
    "tamil": (
        "உங்களுக்குத் தெரிந்தால் சரியான சட்டம் மற்றும் பிரிவு எண்ணைக் குறிப்பிடவும் (எ.கா. \"பாரதீய நியாய சன்ஹிதாவின் பிரிவு 100\") — துல்லியமான மேற்கோள், பொதுவான தலைப்பு விவரணையிலிருந்து முற்றிலும் மாறுபட்ட முறையில் தேடப்படுகிறது.",
        "நீங்கள் கேட்கும் விதி அல்லது சட்டம் இந்த Knowledge Base-இல் இன்னும் உண்மையில் இல்லாமல் இருக்கலாம், இது சொல்லாடல் பிரச்சினை இல்லாமல் இருக்கலாம் — சரிபார்க்க அருகிலுள்ள, தொடர்புடைய கேள்வியை முயற்சிக்கவும்.",
        "தொடர்புடைய ஆவணம் உங்களிடம் இருந்தால், அதைப் பதிவேற்றினால் நான் நேரடியாக அதிலிருந்து பதிலளிக்க முடியும்.",
        "உங்கள் குறிப்பிட்ட உண்மைகள் மீது சட்டம் உண்மையில் என்ன கூறுகிறது என்பதை, இங்குள்ள தேடல் அல்ல, தகுதியான வழக்கறிஞர் மட்டுமே உறுதிப்படுத்த முடியும்.",
    ),
    "telugu": (
        "మీకు తెలిస్తే ఖచ్చితమైన చట్టం మరియు సెక్షన్ నంబర్‌ను తెలియజేయండి (ఉదా. \"భారతీయ న్యాయ సంహిత సెక్షన్ 100\") — ఖచ్చితమైన ఉల్లేఖనం, అంశం యొక్క సాధారణ వివరణ కంటే పూర్తిగా భిన్నంగా శోధించబడుతుంది.",
        "మీరు అడుగుతున్న నిబంధన లేదా చట్టం ఈ Knowledge Base లో ఇంకా నిజంగా లేకపోవచ్చు, ఇది పదాల సమస్య కాకపోవచ్చు — నిర్ధారించుకోవడానికి దగ్గరి, సంబంధిత ప్రశ్నను ప్రయత్నించండి.",
        "సంబంధిత పత్రం మీ వద్ద ఉంటే, దాన్ని అప్‌లోడ్ చేస్తే నేను నేరుగా దాని నుండి సమాధానం ఇవ్వగలను.",
        "మీ నిర్దిష్ట వాస్తవాలపై చట్టం నిజంగా ఏమి చెబుతుందో, ఇక్కడి శోధన కాదు, అర్హతగల న్యాయవాది మాత్రమే నిర్ధారించగలరు.",
    ),
    "urdu": (
        "اگر آپ کو معلوم ہو تو صحیح ایکٹ اور سیکشن نمبر بتائیں (مثلاً \"بھارتیہ نیائے سنہتا کی سیکشن 100\") — درست حوالہ، موضوع کی عمومی تفصیل سے بالکل مختلف انداز میں تلاش کیا جاتا ہے۔",
        "جس شق یا ایکٹ کے بارے میں آپ پوچھ رہے ہیں وہ ابھی اس Knowledge Base میں واقعی موجود نہ ہو، یہ الفاظ کا مسئلہ نہ ہو — تصدیق کے لیے کوئی قریبی، متعلقہ سوال آزمائیں۔",
        "اگر متعلقہ دستاویز آپ کے پاس ہے، تو اسے اپ لوڈ کرنے پر میں براہ راست اسی سے جواب دے سکتا ہوں۔",
        "آپ کے مخصوص حقائق پر قانون اصل میں کیا کہتا ہے، یہ صرف ایک مستند وکیل ہی واضح کر سکتا ہے، یہاں کی تلاش نہیں۔",
    ),
    # Assistant-authored, NOT native-speaker reviewed (same caveat as every
    # non-Hindi entry here). Bodo, Manipuri (Meetei Mayek), Santali (Ol Chiki)
    # and Kashmiri are deliberately left out: better a consistent English
    # fallback than unreviewed legal guidance in a script this module can't
    # vouch for.
    "nepali": (
        "यदि थाहा छ भने ठ्याक्कै ऐन र दफा नम्बर बताउनुहोस् (जस्तै \"भारतीय न्याय संहिताको दफा १००\") — ठ्याक्कै उद्धरणले विषयको सामान्य विवरणभन्दा पूर्ण रूपमा फरक तरिकाले खोज्छ।",
        "तपाईंले सोध्नुभएको प्रावधान वा ऐन यो Knowledge Base मा अहिलेसम्म साँच्चै नहुन सक्छ, यो शब्दावलीको समस्या नहुन पनि सक्छ — जाँच गर्न नजिकको, सम्बन्धित प्रश्न प्रयास गर्नुहोस्।",
        "यदि सम्बन्धित कागजात तपाईंसँग छ भने, त्यसलाई अपलोड गर्दा म सिधै त्यसैबाट जवाफ दिन सक्छु।",
        "तपाईंका विशिष्ट तथ्यहरूमा कानूनले वास्तवमा के भन्छ, त्यो यहाँको खोजले होइन, योग्य अधिवक्ताले मात्र पुष्टि गर्न सक्छन्।",
    ),
    "maithili": (
        "जँ बुझल हुए तँ ठीक अधिनियम आ धारा संख्या बताउ (जेना \"भारतीय न्याय संहिताक धारा १००\") — ठीक उद्धरण विषयक सामान्य विवरणसँ बिल्कुल भिन्न तरहेँ ताकल जाइत अछि।",
        "भऽ सकैत अछि अहाँ जे प्रावधान वा अधिनियमक बारेमे पुछि रहल छी से एखन एहि Knowledge Base मे अछिये नहि — ई मात्र शब्दक समस्या नहि भऽ सकैत अछि; जाँचबाक लेल कोनो लगक, संबंधित प्रश्न आजमाउ।",
        "जँ संबंधित दस्तावेज अहाँक लग अछि तँ ओकरा अपलोड कएलासँ हम सोझे ओहीसँ उत्तर दऽ सकैत छी।",
        "अहाँक विशिष्ट तथ्य पर कानून वास्तवमे की कहैत अछि, से कोनो योग्य अधिवक्ता टा स्पष्ट कऽ सकैत छथि, एतुका खोज नहि।",
    ),
    "sanskrit": (
        "यदि ज्ञायते तर्हि निश्चितम् अधिनियमं धारासङ्ख्यां च कथयतु (यथा \"भारतीयन्यायसंहितायाः धारा १००\") — निश्चितम् उद्धरणं विषयस्य सामान्यवर्णनात् सर्वथा भिन्नरूपेण अन्विष्यते।",
        "भवान् यं प्रावधानम् अधिनियमं वा पृच्छति सः इदानीम् अस्मिन् Knowledge Base इत्यत्र वस्तुतः न स्यात्, शब्दप्रयोगदोषः एव न स्यात् — परीक्षितुं समीपस्थं सम्बद्धं प्रश्नं प्रयतताम्।",
        "यदि सम्बद्धं पत्रं भवतः समीपे अस्ति तर्हि तद् आरोप्य अहं साक्षात् तस्मादेव उत्तरं दातुं शक्नोमि।",
        "भवतः विशिष्टतथ्येषु विधिः वस्तुतः किं वदति इति योग्यः अधिवक्ता एव निश्चिनोति, अत्रत्या अन्वेषणा न।",
    ),
    "konkani": (
        "जाणा आसल्यार अचूक कायदो आनी कलम क्रमांक सांगात (उदा. \"भारतीय न्याय संहितेचें कलम १००\") — अचूक उल्लेख, विशयाच्या सादारण वर्णनापरस पुरायपणान वेगळ्या तरेन सोदतात.",
        "तुमी विचारता तो तरतूद वा कायदो ह्या Knowledge Base त अजून खरेंच नासूं येता, शब्दरचनेची समस्या नासूंय येता — तपासपाखातीर लागींचो, संबंदीत प्रस्न वापरून पळयात.",
        "संबंदीत दस्तावेज तुमचेकडेन आसल्यार, तो अपलोड केल्यार हांव थेट तातूंतल्यानच जाप दिवं येता.",
        "तुमच्या विशिश्ट तथ्यांचेर कायदो प्रत्यक्षांत कितें सांगता तें पात्र वकीलच सांगूं शकता, हांगाच्या सोदान न्हय.",
    ),
    "dogri": (
        "जेकर पता होऐ तां ठीक अधिनियम ते धारा नंबर दस्सो (जियां \"भारतीय न्याय संहिता दी धारा १००\") — ठीक हवाला, विषय दे आम ब्योरे कोला बिल्कुल बक्खरे ढंगें कन्नै खोजेआ जंदा ऐ।",
        "होई सकदा ऐ तुस जिस प्रावधान जां अधिनियम बारै पुच्छा करदे ओ, ओह् इस Knowledge Base च हून तगर सच्चें ई नेईं होऐ — एह् सिर्फ शब्दें दी समस्या नेईं होई सकदी; जांचने आस्तै कोई नेड़ला, संबंधत सवाल आजमाओ।",
        "जेकर संबंधत दस्तावेज़ तुंदे कोल ऐ तां उसी अपलोड करने पर मैं सीधा उसी चा जवाब दे सकना।",
        "तुंदे खास तथ्यें पर कानून असल च केह् आखदा ऐ, एह् कोई योग्य वकील ई साफ करी सकदा ऐ, इत्थूं दी खोज नेईं।",
    ),
    "assamese": (
        "যদি জানে তেন্তে সঠিক আইন আৰু ধাৰা নম্বৰ কওক (যেনে \"ভাৰতীয় ন্যায় সংহিতাৰ ধাৰা ১০০\") — সঠিক উদ্ধৃতি বিষয়ৰ সাধাৰণ বিৱৰণতকৈ সম্পূৰ্ণ পৃথকভাৱে সন্ধান কৰা হয়।",
        "আপুনি সোধা বিধান বা আইন এই Knowledge Base ত এতিয়াও সঁচাকৈয়ে নাথাকিব পাৰে, ই শব্দ-প্ৰয়োগৰ সমস্যা নহবও পাৰে — পৰীক্ষা কৰিবলৈ ওচৰৰ, সম্পৰ্কিত প্ৰশ্ন এটা চেষ্টা কৰক।",
        "সংশ্লিষ্ট নথি আপোনাৰ ওচৰত থাকিলে, সেয়া আপলোড কৰিলে মই পোনপটীয়াকৈ তাৰ পৰাই উত্তৰ দিব পাৰো।",
        "আপোনাৰ নিৰ্দিষ্ট তথ্যৰ ওপৰত আইনে আচলতে কি কয়, সেয়া ইয়াৰ সন্ধানে নহয়, যোগ্য অধিবক্তাইহে নিশ্চিত কৰিব পাৰে।",
    ),
    "sindhi": (
        "جيڪڏهن خبر هجي ته صحيح ايڪٽ ۽ سيڪشن نمبر ٻڌايو (مثال \"ڀارتي نيا سنهتا جو سيڪشن 100\") — صحيح حوالو، موضوع جي عام بيان کان بلڪل مختلف نموني ڳولهيو ويندو آهي.",
        "ٿي سگهي ٿو ته توهان جنهن شق يا ايڪٽ بابت پڇو ٿا اهو اڃا هن Knowledge Base ۾ حقيقت ۾ موجود نه هجي، اهو لفظن جو مسئلو نه به ٿي سگهي ٿو — جاچڻ لاءِ ڪو ويجهو، لاڳاپيل سوال آزمايو.",
        "جيڪڏهن لاڳاپيل دستاويز توهان وٽ آهي ته ان کي اپلوڊ ڪرڻ سان مان سڌو ان مان جواب ڏئي سگهان ٿو.",
        "توهان جي مخصوص حقيقتن تي قانون اصل ۾ ڇا چوي ٿو، اهو صرف هڪ مستند وڪيل ئي واضح ڪري سگهي ٿو، هتان جي ڳولا نه.",
    ),
}


def generic_next_steps_guidance(language: str | None) -> str:
    """The non-urgent counterpart to `actionable_guidance`: concrete next
    steps for an ORDINARY informational question that found no verified
    source, as opposed to a safety situation. Never returns "" -- unlike
    `actionable_guidance`, there is no "this doesn't need guidance" case
    here; every strict-RAG refusal that isn't already covered by an urgency
    category reaches this instead (see `_no_verified_context_answer`)."""
    resolved = (language or "english").strip().lower()
    if resolved not in _GENERIC_NEXT_STEPS:
        # Heading and steps must come from the SAME language: a language in
        # `_HEADINGS` but not here would otherwise get a native heading over
        # English steps.
        resolved = "english"
    steps = _GENERIC_NEXT_STEPS[resolved]
    lines = [f"**{_localized(_HEADINGS, resolved)}**", ""]
    lines.extend(f"{index}. {step}" for index, step in enumerate(steps, start=1))
    return "\n".join(lines)


def actionable_guidance(
    question: str, language: str | None, template_name: str | None = None, template_command: str | None = None
) -> str:
    """The block appended to a strict-RAG refusal, or `""` when the question
    isn't one where a bare refusal leaves the user stranded.

    `template_name` is the already-localized display name of a draft this app
    can produce for the situation, and `template_command` its English name
    (what the user should actually type); the caller resolves both, since this
    module has no business importing the drafting package.
    """
    category = detect_category(question)
    if category is None:
        return ""
    resolved = (language or "english").strip().lower()
    if resolved not in _STEPS:
        # Languages that only have the generic-guidance tables (see
        # `_GENERIC_NEXT_STEPS`) get the WHOLE urgent block in English rather
        # than a native heading over English steps.
        resolved = "english"
    # `_STEPS`, `_HEADINGS`, `_CHANNEL_LABELS`, `_SOURCE_NOTES` and (since the
    # BUG-01/BUG-02 fix) `_DRAFT_OFFERS` all cover the identical 13-language
    # set deliberately -- every line of this block must resolve together, or
    # a language in one table but not another produces a same-block script
    # mix instead of a clean single-language fallback. A language outside all
    # of them falls back to English steps rather than showing nothing.
    steps = _STEPS.get(resolved, _STEPS["english"]).get(category.key) or _STEPS["english"][category.key]
    lines = [
        f"**{_localized(_HEADINGS, resolved)}**",
        "",
        f"*{_localized(_CHANNEL_LABELS, resolved)}:* " + " · ".join(_CHANNELS[category.key]),
        "",
    ]
    lines.extend(f"{index}. {step}" for index, step in enumerate(steps, start=1))
    if template_name:
        lines.append("")
        lines.append(
            _localized(_DRAFT_OFFERS, resolved).format(
                template=template_name, command=template_command or template_name
            )
        )
    lines.append("")
    lines.append(f"> {_localized(_SOURCE_NOTES, resolved)}")
    return "\n".join(lines)
